### PR TITLE
Add/replace modules icon and update manifest

### PR DESCRIPTION
**Pull request by shmshd**
SVG icons are from [material-design-icons](https://pictogrammers.com/library/mdi/). 

Before | After
-|-
settings_before | settings_after
extensions_before|extensions_after

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Maybe for consistency we should go with https://tabler-icons.io

**Comment by BelleNottelling** [comment]
These icons look good, don't we need to notate the license for the icons somewhere though? (Should be Apache 2.0: https://pictogrammers.com/docs/general/license/)

**Comment by shmshd** [comment]
To be honest I have no idea about legal stuffs. FYI, I did modify the SVG files by adding `fill="currentColor"`.

Should this icon source be mentioned in the README.md as per the license?

**Comment by BelleNottelling** [comment]
> To be honest I have no idea about legal stuffs. FYI, I did modify the SVG files by adding `fill="currentColor"`.
> 
> Should this icon source be mentioned in the README.md as per the license?

Modifying it isn't an issue at all, but yes, I believe that because we have the icons as part of our source code we need to mention where they come from and their associated license. A note in the read me should probably be sufficient. To be honest, I'm not entirely certain about it all either, and I wouldn't' be surprised if we had quite a few instances where the licensing for dependencies aren't being 100% adhered to, especially with content that was added with BoxBilling before we forked it.

**Comment by shmshd** [comment]
@jaapmarcus Could you update the license note for the icon in README?

**Review by evrifaessa — APPROVED** [review]
Looks great. Should be good to merge once the attribute is added.

**Comment by evrifaessa** [comment]
By the way:

"We'd love attribution in your app's about screen, but it's not required."
-- https://developers.google.com/fonts/docs/material_icons#licensing

**Comment by BelleNottelling** [comment]
> By the way:
> 
> "We'd love attribution in your app's about screen, but it's not required." -- https://developers.google.com/fonts/docs/material_icons#licensing

These icons aren't the google material icons. They are from [pictogrammers](https://pictogrammers.com/)

**Comment by shmshd** [comment]
> These icons aren't the google material icons. They are from [Pictogrammers](https://pictogrammers.com/)

and here is their GitHub repo https://github.com/Templarian/MaterialDesign for this icon set.

**Comment by jaapmarcus** [comment]
> Looks great. Should be good to merge once the attribute is added.

In that case we should also list:
https://github.com/tabler/tabler-icons/
And other 3rd party software...

**Comment by BelleNottelling** [comment]
> > Looks great. Should be good to merge once the attribute is added.
> 
> In that case we should also list: https://github.com/tabler/tabler-icons/ And other 3rd party software...

There is likely a lot of things we need to attribute, and at some point an audit would likely be good, but for now I am far more concerned about things we actually include in part of our source code rather than something that's installed through a package manager.

**Comment by evrifaessa** [comment]
I added attribution. Mind checking? @BelleNottelling @jaapmarcus

**Review by BelleNottelling — APPROVED** [review]

**Pull request merged**
