### PR TITLE
Remove modernizr from Huraga

### PR DESCRIPTION
**Pull request by BelleNottelling**
It wasn't being used

### CODE REVIEW

**Comment by John-S4** [comment]
Are you sure about all of these?

It looks to me like the font-awesome.css is being used in the side nav, even if nowhere else. 

See attached screen grab. 

Screenshot (25)

**Comment by BelleNottelling** [comment]
> Are you sure about all of these?
> 
> It looks to me like the font-awesome.css is being used in the side nav, even if nowhere else. 
> 
> See attached screen grab. 
> 
> Screenshot (25)
> 

I'm not anymore. Somehow I got it into my head that the font-awesome prefix was `fa-` so that's what I looked for in the code

**Comment by John-S4** [comment]
> I'm not anymore. Somehow I got it into my head that the font-awesome prefix was `fa-` so that's what I looked for in the code

Yep, if you are calling the icons using <icon> or <i> then it would have an 'fa-' prefix, but here they have specified Font Awesome as the font, and then called them as unicode characters.

**Comment by BelleNottelling** [comment]
> > I'm not anymore. Somehow I got it into my head that the font-awesome prefix was `fa-` so that's what I looked for in the code
> 
> Yep, if you are calling the icons using `<ico>` or `<i>` then it would have an 'fa-' prefix, but here they have specified Font Awesome as the font, and then called them as unicode characters.

Alright. I restored font-awesome. Thanks for the catch

**Review by John-S4 — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
