### PR TITLE
Update dependencies for NPM 

### PR DESCRIPTION
**Pull request by jaapmarcus**

### CODE REVIEW

**Comment by John-S4** [comment]
I'm a bit confused... it seems like some of these are updated to newer versions, but some are lower version numbers?

**Comment by jaapmarcus** [comment]
Unless we manually updated  it doesn't make a lot of sense.

node_modules/dom-serializer is for example down graded

**Comment by BelleNottelling** [comment]
We already have GitHub actions configured for NPM packages?
https://github.com/FOSSBilling/FOSSBilling/blob/main/.github/dependabot.yml

**Comment by jaapmarcus** [comment]
> We already have dependabot configured for NPM packages?
> https://github.com/FOSSBilling/FOSSBilling/blob/main/.github/dependabot.yml

Why are there so many out of date... 

But it is strange...

**Pull request closed without merging**
