### PR TITLE
Improved Customer Mobile Navigation (#2031) + Auth Flow Design

### PR DESCRIPTION
**Pull request by wolveix**
This closes out https://github.com/FOSSBilling/FOSSBilling/issues/2031. I duplicated the sidebar menu items into a seperate template specifically for mobile (as re-using wouldn't work well), and only show the sidebar items in the top menu if the user is on mobile. I also hide the normal top menu items for mobile users, as the functionality is duplicated between the two menus.

I also took this as an opportunity to improve the design of the UI elements throughout the auth flow. While the move to Bootstrap 5 has drastically improved the customer dashboard, the buttons and badges don't align well (the colouring being one of the biggest issues). I figured I'd test the waters with moving the secondary buttons to use outlined buttons (as is consistent elsewhere), and see what you thought :)

Thanks!

### CODE REVIEW

**Comment by wolveix** [comment]
New menu bar for mobile users:
Screenshot 2024-01-05 at 14 38 06

New login page buttons:
Screenshot 2024-01-05 at 14 39 11

New sign up page buttons:
Screenshot 2024-01-05 at 14 39 27

New forgot a password page buttons:
Screenshot 2024-01-05 at 14 39 34

**Review by BelleNottelling — APPROVED** [review]
Looks pretty nice, thanks.
I think the language selector looks a bit odd, but I don't know how much we can do about that really

**Comment by wolveix** [comment]
Thanks! I agree with you there. I figured I'd leave it as-is until I had some more time to mess around with it

**Review by jaapmarcus — APPROVED** [review]

**Comment by BelleNottelling** [comment]
Hey @wolveix could you get this up-to-date with our main branch so it can be merged?
Thanks!

**Comment by wolveix** [comment]
@BelleNottelling done and done! :)

**Pull request merged**
