### PR TITLE
Replace Gulp with Webpack Encore

### PR DESCRIPTION
**Pull request by shmshd**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
It still tries to use gulp for building the test build

**Comment by shmshd** [comment]
> It still tries to use gulp for building the test build

Yes. Gulp command is in the workflow (https://github.com/FOSSBilling/FOSSBilling/blob/main/.github/workflows/artifact.yml#L64). Should update that as well

**Comment by BelleNottelling** [comment]
> > It still tries to use gulp for building the test build
> 
> Yes. Gulp command is in the workflow (https://github.com/FOSSBilling/FOSSBilling/blob/main/.github/workflows/artifact.yml#L64). Should update that as well

Yes, that workflow needs to be updated for the new method. We use it both for testing new PRs and as a convenient way to create a new build during the release process.

**Comment by shmshd** [comment]
Because of the use of Purgecss, this PR should be tested with quite a bit of data to see if it removes the used CSS. I do not have enough data to do a thorough check.

**Comment by BelleNottelling** [comment]
> Because of the use of Purgecss, this PR should be tested with quite a bit of data to see if it removes the used CSS. I do not have enough data to do a thorough check.

It must not be removing a lot, as this build is actually larger than the most recent [preview build](https://fossbilling.org/downloads/preview).
Latest preview on the left, this build on the right:
image

On the subject of stripping out unused CSS, I'm honestly not sure that's the best move here, as custom modules will have to use whatever CSS is provided by the current theme. It's probably really unlikely that we would have stripped out CSS that's needed by a custom module, but it's pretty hard to know

**Comment by shmshd** [comment]
> It must not be removing a lot, as this build is actually larger than the most recent [preview build]

I think that isn't a fair comparison as the vendor dir itself has 700+ files from the 2 packages added for the twig extension. 
In addition to that I have set Webpack to build the images from `admin_default/images` to `admin_default/build` dir which brings in 31 images. This is set for future image optimization if needed but can be disabled.

 46 SVG files are also generated with js content from `svg-sprite-loader` which I need help to disable it.

**Comment by BelleNottelling** [comment]
> > It must not be removing a lot, as this build is actually larger than the most recent [preview build]
> 
> I think that isn't a fair comparison as the vendor dir itself has 700+ files from the 2 packages added for the twig extension. In addition to that I have set Webpack to build the images from `admin_default/images` to `admin_default/build` dir which brings in 31 images. This is set for future image optimization if needed but can be disabled.
> 
> 46 SVG files are also generated with js content from `svg-sprite-loader` which I need help to disable it.

The slight increase in file size is fine, really, especially now knowing where it's coming from.

However, none of that changes my 2nd comment, regarding removing the unused CSS.
While it is a nice idea, any custom modules will be using the same CSS files, so we don't really have a way of ensuring what classes will always be used. While our main source dir very possibly has all of the CSS classes someone might want to use in their custom module, there might be edge-cases where it's not there.

I'd like to hear opinions from other team members (@jaapmarcus, @John-S4, and @evrifaessa) to see if we want to be concerned about that, or if we don't think it'll have any real-world impact

**Comment by shmshd** [comment]
> However, none of that changes my 2nd comment, regarding removing the unused CSS. While it is a nice idea, any custom modules will be using the same CSS files, so we don't really have a way of ensuring what classes will always be used. While our main source dir very possibly has all of the CSS classes someone might want to use in their custom module, there might be edge-cases where it's not there.

Purgecss currently is scanning all the `*.html.twig` in the `src` dir and `admin_default/assets/**/*.js` files (https://github.com/shmshd/FOSSBilling/blob/gulp-to-encore/src/themes/admin_default/postcss.config.js#L8-L10). So, all modules should work fine (theoretically).

Classes like `flag-XX` need to be safelisted as it completely appears only on the existence of the data (https://github.com/shmshd/FOSSBilling/blob/gulp-to-encore/src/themes/admin_default/postcss.config.js#L12-L14). I couldn't find any similar classes due to lack of data.

**Comment by BelleNottelling** [comment]
> Purgecss currently is scanning all the `*.html.twig` in the `src` dir and `admin_default/assets/**/*.js` files (https://github.com/shmshd/FOSSBilling/blob/gulp-to-encore/src/themes/admin_default/postcss.config.js#L8-L10). So, all modules should work fine (theoretically).

Custom themes as in not ones we write and that are not a part of our source code.

**Comment by shmshd** [comment]
Please note that `jquery@3.6` in `admin_default/package.json` is installed for the use of `spectrum-colorpicker` only. `admin_default` theme is currently using `jquery@1.7` which is already in the assets dir. It is not easily replaceable and it was not the intention of this PR as well.

**Comment by shmshd** [comment]
> Custom modules as in not ones we write and that are not a part of our source code.

I never thought of it and yes, it could bring in design issues.

**Comment by John-S4** [comment]
> I'd like to hear opinions from other team members (@jaapmarcus, @John-S4, and @evrifaessa) to see if we want to be concerned about that, or if we don't think it'll have any real-world impact

I think it is something that we should be concerned with to be honest. As much as I am all for stripping out unnecessary things and just generally making things as light and without bloat as possible, I don't think that we should be using Purgecss here for the reasons above. 

The replacement of Gulp with Webpack I'm all in for apart from that though.

**Comment by jaapmarcus** [comment]
We need to go and check if certain css styles are used in other modules and in the future stream line as much as possible

**Comment by shmshd** [comment]
Purgecss is removed

**Review by jaapmarcus — APPROVED** [review]

**Comment by evrifaessa** [comment]
I'm planning to test and review this today.

**Review by evrifaessa — APPROVED** [review]
Looks fine. Thanks for the great PR. Could you resolve the merge conflict?

**Comment by shmshd** [comment]
This PR closes #278 as it is irrelevant now.

**Review by BelleNottelling — APPROVED** [review]
Looks great, thank you

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
