### PR TITLE
Sync .pot file with source code

### PR DESCRIPTION
**Pull request by BelleNottelling**
I bought the pro version of Poedit which then let me update the translations.
I then also used the pre-translate option to pre-translate a few languages.

I tested on my system, but it doesn't seem like the translation system is working.
@jaapmarcus can you try it? I know you said that they seemed to work for you

### CODE REVIEW

**Review by jaapmarcus — COMMENTED** [review]
Use es_ES instead of es 
And it should work fine
Screenshot 2022-12-06 at 10 11 02

And 
Screenshot 2022-12-06 at 10 10 53

**Comment by jaapmarcus** [comment]
Also I am not a fan of keeping the .po files in the main repo. They create a lot of "noise" due to all the references in .po where the translations can be found. 

We should move them to a remote repo!

**Comment by evrifaessa** [comment]
Yes, I eventually will bring localization file support to the extension store. Let’s keep it in a separate repo.

**Comment by BelleNottelling** [comment]
I've removed the new locales from this repo so we can add them to a new one. This PR is ready to be merged

**Review by evrifaessa — APPROVED** [review]
LGTM. Great PR. We should automate doing this periodically someday.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
