### PR TITLE
Update mod_invoice_index.html.twig

### PR DESCRIPTION
**Pull request by alicom13**
Responsive Table invoice

### CODE REVIEW

**Comment by shmshd** [comment]
Out of curiosity, why not use this class on table element?

**Comment by jaapmarcus** [comment]
If we want it on the table class we should also update
https://github.com/FOSSBilling/FOSSBilling/commit/b1fe4346fa1aef8e5983f7821ad0343e1d2b7e7f

**Comment by shmshd** [comment]
yes that file also needs an update if it works fone at table tag. Additional div is unnecessary.

**Comment by John-S4** [comment]
@alicom13 Please can you take a look at the questions above and if there is a specific valid reason for the additional div then we can merge this, if not then it can be updated to apply the class to the table instead, or the PR can just be closed.

**Review by admdly — APPROVED** [review]

**Review by BelleNottelling — APPROVED** [review]

**Pull request merged**
