### PR TITLE
Decrease timeout ssl check

### PR DESCRIPTION
**Pull request by jaapmarcus**
60 seconds is to long and should be shorter. 

In future to be "rewritten" to use the composer libraries

### CODE REVIEW

**Comment by BelleNottelling** [comment]
> In future to be "rewritten" to use the composer libraries

If there's already a composer package to check for a valid SSL cert on the server, we should be using that

**Review by admdly — APPROVED** [review]

**Comment by admdly** [comment]
After reviewing this - there are ways to do this - the method currently used being one of the most popular and frankly quire clever. However, why should we care, as an application about global validity? Going forward we should assume good faith, and let system admins worry about whether certs are valid.

**Comment by BelleNottelling** [comment]
> After reviewing this - there are ways to do this - the method currently used being one of the most popular and frankly quire clever. However, why should we care, as an application about global validity? Going forward we should assume good faith, and let system admins worry about whether certs are valid.

We do this check because we want to force HTTPs whenever possible, and currently that option is enabled or disabled depending on if the installer is loaded via HTTPs. So if we can detect the server has a valid cert, we can then redirect them to the HTTPs page and force HTTPs in FOSSBilling once installed.

**Comment by admdly** [comment]
> > After reviewing this - there are ways to do this - the method currently used being one of the most popular and frankly quire clever. However, why should we care, as an application about global validity? Going forward we should assume good faith, and let system admins worry about whether certs are valid.
> 
> We do this check because we want to force HTTPs whenever possible, and currently that option is enabled or disabled depending on if the installer is loaded via HTTPs. So if we can detect the server has a valid cert, we can then redirect them to the HTTPs page and force HTTPs in FOSSBilling once installed.
> 
> Edit: Here's the line in the installer that I'm referencing: https://github.com/FOSSBilling/FOSSBilling/blob/main/src/install/install.php#L471

Fair enough - can't disagree - personally never seen software go this far, but glad we do. 😄

**Pull request merged**
