### PR TITLE
Make the Formbuilder slightly less ugly

### LINKED ISSUE #886: [Bug] Form builder input fields no displaying correctly
### Describe the bug

Input fields utilise lists without properly setting the list style to none

### How to reproduce

Go to admin panel
Create a custom form
Create any field

### Expected behavior

No list style to be present (there not to be bullet points)

### Screenshots

image
image

### FOSSBilling version

0.3.0

### Module version

formbuilder

### Device

_No response_

### Information

- OS: Windows 11
- Browser: Google Chrome 110.0.5481.178, MS Edge 110.0.1587.57
- Version 0.3.0

> I have reproduced this on both a private and the demo instance

### Additional context

This doesn't break anything, it just doesn't look correct

### PR DESCRIPTION
**Pull request by BelleNottelling**
Closes #886
It hides the bullet points, and even updates a few items to use Tabler / Bootstrap styling. I was going to do more.. but this module's styling is a mess and front-end is far from my best skill.
image
image

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]
Definitely an improvement.

Of course not in the scope of this PR but in the future, we should remove this module's jQuery dependency and use [Tabler's modals](https://preview.tabler.io/modals.html) instead of jConfirm.

**Comment by BelleNottelling** [comment]
> Definitely an improvement.
> 
> Of course not in the scope of this PR but in the future, we should remove this module's jQuery dependency and use [Tabler's modals](https://preview.tabler.io/modals.html) instead of jConfirm.

We may as well re-write the user facing portion of the module if we are going to do that, it's a mess. I think it'll be less work to re-write than to slowly fix it up

**Review by admdly — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Comment by BradBot1** [comment]
TYSM! This drove me insane like actually <3

**Comment by BelleNottelling** [comment]
> TYSM! This drove me insane like actually <3

Welcome!

**Pull request merged**
