### PR TITLE
Change how we load locale names

### PR DESCRIPTION
**Pull request by jaapmarcus**
Current "System" depends on the locale translation in the current local. 

Option 1:  Keep as is ignore this PR 
Option 2: Create a new file in Locale repo and add there the follow key pair
'en_US' => 'English',
'nl_NL' => 'Nederlands'

And apply the changes as suggested. See for the following screenshots

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Before: 
Screenshot 2022-12-19 at 14 08 03

After:
Screenshot 2022-12-19 at 13 59 54

Admin (Before)
Screenshot 2022-12-19 at 14 09 50


Admin: (After)
Screenshot 2022-12-19 at 14 10 33

**Comment by jaapmarcus** [comment]
Also please note there is  breaking change with existing "custom" templates that have support for the same localisation as we have.

**Comment by BelleNottelling** [comment]
> Also please note there is breaking change with existing "custom" templates that have support for the same localisation as we have.

Do you mean custom themes?

**Comment by jaapmarcus** [comment]
Yes :)

**Comment by BelleNottelling** [comment]
> Yes :)

Will it completely break existing themes, or will they just not be able to change the language selection?

**Comment by jaapmarcus** [comment]
It breaks due to the changes in:
` <li class="language_selector" data-language-code="{{ lang.locale }}"><a href="javascript:;"> <span class="flag {{ countryCode | lower }}"></span> {{ lang.title }}</a></li>`

lang was first an "string" and it became an array see:
https://github.com/FOSSBilling/FOSSBilling/pull/611/commits/122b63859cf7d76ed51383f15870cf0725021923

Ideally we should "clean" up the translation files and remove all the existing languages declarations

**Comment by jaapmarcus** [comment]
Added backwards compability to it by adding a $deep var in languages() function

**Review by BelleNottelling — APPROVED** [review]

**Review by John-S4 — APPROVED** [review]
With the added backwards comparability, all seems good to me.

**Pull request merged**
