### PR TITLE
Minor updates to the admin layout

### PR DESCRIPTION
**Pull request by evrifaessa**
I've changed the navbar a little bit and adjusted the page width to make it more readable.

Current layout:
Current

Proposed:
New

### CODE REVIEW

**Comment by BelleNottelling** [comment]
The only thing I would say is to maybe move everything in half as much. Still gives a bit more space and makes it feel less cramped, but also gives up less overall space for the info in the middle

**Review by BelleNottelling — APPROVED** [review]

**Comment by jaapmarcus** [comment]
I agree with @BelleNottelling ...  This is a bit to much white space

**Comment by John-S4** [comment]
What screen resolution are those two images?

Personally, I don't have an issue with the amount of space in the WIP, I think it looks clean. I'm assuming that's a pretty wide screen res and the spaces shrink pretty rapidly as you resize?

**Comment by BelleNottelling** [comment]
This is how it looks on 2560x1440.. and that's a lot of empty space
image
And 1280x720 (simulated through chrome's dev tools)
image

**Comment by xSido** [comment]
https://user-images.githubusercontent.com/45123194/199856639-f7661104-2108-4377-bd76-bdd78b75ba9d.mp4

**Comment by John-S4** [comment]
@xSido That capture looks like the existing install not the proposed changes?

@BelleNottelling I get what you are saying, but how many actually will work in FOSSB admin with that screen res and a full screen window, I know I don't. Not dismissing what you are saying, just thinking aloud. 

I'm going to approve the review because to me these changes make sense, and it is a visual improvement. I suggest not merging until we can get any other opinions or a compromise of some kind between what @evrifaessa is proposing and @BelleNottelling and @jaapmarcus whitespace concerns.

**Review by John-S4 — APPROVED** [review]

**Comment by BelleNottelling** [comment]
@John-S4 while I don't disagree, the vast majority are on 1080p, high resolution monitors are becoming more affordable and are gaining in popularity. Steam hardware survey shows 1080p has lost usage and 1440p has gone up. And the latest generation of GPUs are boasting the ability to pay games in 8k.

Yes that will be less common in a work environment, but it absolutely is gaining popularity and is almost definitely the way that the entire industry is going. Many work / professional laptops already come with 1440p or 4k screens. I really do think it is important that the experience is good on those as well.

**Comment by evrifaessa** [comment]
I think I can revert the whitespace changes and only get the navbar change merged at this phase.

**Comment by John-S4** [comment]
> I think I can revert the whitespace changes and only get the navbar change merged at this phase.

I think maybe that is a good compromise for now, and keep the whitespace changes for a future update.

**Pull request merged**
