### PR TITLE
Drop the BB prefix

### PR DESCRIPTION
**Pull request by BelleNottelling**
1) This is no longer BoxBilling
2) It just doesn't need to be there & now is the time to make changes like these

### CODE REVIEW

**Comment by Komodroid** [comment]
Does it affect the internal filesystem? remember that most modules are inside */bb/* folders (maybe another issue)

**Comment by BelleNottelling** [comment]
> Does it affect the internal filesystem? remember that most modules are inside `*/bb/*` folders (maybe another issue)

Yes, this changes everything and is potentially hugely breaking.. but anything that is properly written shouldn't have hardcoded paths and instead use pre-existing variables which I updated, and since this is a new project this is our time to make these breaking changes, before FOSSBilling makes it's first release

**Comment by BelleNottelling** [comment]
### Renames:
**Files:**
`src/bb-load.php` -> `src/load.php`
`src/bb-ipn.php` -> `src/ipn.php`
`src/bb-di.php` -> `src/di.php`
`src/bb-update.php` -> `src/update.php`
`src/bb-cron.php` -> `src/cron.php`
`src/bb-config.php` -> `src/config.php`
`src/bb-config-sample.php` -> `config-sample.php`

**Folders:**
`src/bb-library` -> `src/ibrary`
`src/bb-data` -> `src/data`
`src/bb-themes` -> `src/themes`
`src/bb-uploads` -> `src/uploads`
`src/bb-modules` -> `src/modules`
`src/bb-locale` -> `src/locale`
`tests/bb-library` -> `test/library`
`test/bb-modules` -> `tests/modules`
`tests/integrations/bb-library` -> `tests/integrations/library`
`tests/integrations/bb-modules` -> `tests/integrations/modules`

Also updated files references and paths across the entire codebase

**Comment by andpavlenko** [comment]
Don't srop. Go ahead: https://github.com/boxbilling/boxbilling/issues/1262#issuecomment-1090667033

**Comment by jaapmarcus** [comment]
Agree with @andpavlenko and move to the Symfony  directory format  instead

**Comment by BelleNottelling** [comment]
> Don't srop. Go ahead: [boxbilling/boxbilling#1262 (comment)](https://github.com/boxbilling/boxbilling/issues/1262#issuecomment-1090667033)

Maybe we should actually agree on what framework everyone want's to move towards before restructuring to match one?
There's been a little talk about Laravel and Symfony just from a few  of us, I'd like to get input from everyone, see what they are familiar with & what they recommend, and agree on a framework together. (this is assuming that we have the intention to port FOSSBilling to a framework)

**Comment by andpavlenko** [comment]
@BelleNottelling 
You can't to make full migration to anyone framework.
But easy to integrate some isolated components from Symfony, like DI, Doctrine, Security, etc...

**Comment by 0x6b-dev** [comment]
I’ll refer to HunterNyan for code related matters.

From a project management perspective - we’re miles away from a 1.0 release so I don’t mind a bit of breakage.

**Comment by evrifaessa** [comment]
As long as we keep the migration process easy, I'm okay to any changes. This is the phase where we need to make many breaking changes and decide on the future of the project.

**Comment by BelleNottelling** [comment]
> When will this be fixed? 💀

Probably won't tbh, now that we have a new branch where I'm working on a migration to a all new code base, this seems like a waste of time

**Comment by evrifaessa** [comment]
I think we can hold this until we have some progress with Laravel and are comfortable to make our first Laravel release. We can keep the same directory naming to make it compatible with the last version of BB, this way we can still publish some last releases before pulling the plug.

**Comment by evrifaessa** [comment]
oh you already closed it

**Pull request closed without merging**
