### PR TITLE
Huraga: show a dashboard when not logged in

### PR DESCRIPTION
**Pull request by BelleNottelling**
Fix for https://github.com/FOSSBilling/FOSSBilling/issues/298
This PR adds a configurable option to Huraga which either enables or disables a guest dashboard. 
Disabling automatically redirects to the login page as the previous behavior was

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Here's a gif showing that the settings work & showcasing somewhat how the dashboard looks and behaves for guests:
Animation

**Comment by xSido** [comment]
yes please

**Comment by evrifaessa** [comment]
You should also add the new setting to the example configuration file. Ideally the installer copies the example to its original place and uses those as default values.

**Comment by BelleNottelling** [comment]
> You should also add the new setting to the example configuration file. Ideally the installer copies the example to its original place and uses those as default values.

Done

**Review by evrifaessa — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
