### PR TITLE
fix icon

### PR DESCRIPTION
**Pull request by reynaldiarya**

### CODE REVIEW

**Review by John-S4 — COMMENTED** [review]
Since all of these images are the same size, is there a reason for giving them explicit sizing in the html instead of just defining a size for the class in css?

**Comment by jaapmarcus** [comment]
Also please keep the commit history as straight as possible The merge commits from won't help with the readability

Click on the sync fork button.
Screenshot 2023-01-19 at 07 43 30

**Comment by evrifaessa** [comment]
Don’t worry, we can always squash and merge.

**Comment by BelleNottelling** [comment]
> Don’t worry, we can always squash and merge.

A squash merge is fine for small changes, but for larger and more significant changes it can be nice to keep the commit history intact, at which point I'd rather not have the fork having 20+ "Merge branch 'FOSSBilling:main' into main" commits

**Comment by reynaldiarya** [comment]
> Since all of these images are the same size, is there a reason for giving them explicit sizing in the html instead of just defining a size for the class in css?

i just copied the other code

**Comment by reynaldiarya** [comment]
> Also please keep the commit history as straight as possible The merge commits from won't help with the readability
> 
> Click on the sync fork button. Screenshot 2023-01-19 at 07 43 30

before i edit i already do sync fork

**Comment by jaapmarcus** [comment]
The best thing is never edit the main branch but create a branch...

**Review by BelleNottelling — APPROVED** [review]
Fine with me as long as we squash merge.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
