### PR TITLE
User profile settings layout tweaks

### PR DESCRIPTION
**Pull request by evrifaessa**
As a part of #758, I've made some changes to the user profile settings layout.

It still needs a lot of improvements, but I think it's a good start over the old one.

I also am planning to implement WYSIWYG into the "Signature" field, but I'll do it in another PR which will also include a couple of more places that need WYSIWYG implemented.

Old:
image

New:
image
image
image

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by John-S4** [comment]
Looks a lot better in those screengrabs, what happens on mobile / small screens?

**Comment by evrifaessa** [comment]
@John-S4 - Oh wow, it hides the sidebar in mobile view.

Didn't expect this to happen, and definitely don't know how to fix it. 

This is Tabler's own preview website and it's the same in my local FOSSBilling install too.

image

**Comment by evrifaessa** [comment]
I found a related issue in tabler/tabler: https://github.com/tabler/tabler/issues/1304

**Comment by BelleNottelling** [comment]
The sidebar has always been hidden on mobile, your PR didn't change that

**Comment by evrifaessa** [comment]
> The sidebar has always been hidden on mobile, your PR didn't change that 

Not that one. The one that says "My Account", "Password" and "API access"

**Comment by BelleNottelling** [comment]
> > The sidebar has always been hidden on mobile, your PR didn't change that 
> 
> Not that one. The one that says "My Account", "Password" and "API access"

Ah.. so it hides the tabs for that page

**Comment by evrifaessa** [comment]
What should we do with this PR? It seems like a problem on Tabler's end, and I can't think of a possible workaround.

**Comment by BelleNottelling** [comment]
You could get rid of the tabs and make everything available in one view, or turn them into a hamburger menu.

Tabler is built on Bootstrap so there's plenty of CSS classes and functionality that aren't explicitly used on their demo pages

**Comment by John-S4** [comment]
> You could get rid of the tabs and make everything available in one view, 

This sounds like a good way to go :)

> or turn them into a hamburger menu.

Personally I would much rather skip having multiple hamburger menus on the same page, you already have one for the main nav, and then another one for the page sub nav seems messy. The content is not so long that it can't all just be available in one view.

**Comment by shmshd** [comment]
I would suggest you use an Accordion. Something like this:

profile-design

**Comment by shmshd** [comment]
There isn't any navigation to the profile page in the mobile view. We have to go via URL which isn't ideal. Probably we will have to move the hamburger to the left and place the profile avatar dropdown to the right as in the original design.

**Comment by BelleNottelling** [comment]
If everyone is okay with it, I'd like us to go forward with the proposed changes that @shmshd made. 
https://github.com/shmshd/FOSSBilling/tree/evrifaessa-patch-1

**Comment by BelleNottelling** [comment]
Closing as stale.
If someone wants to pick this back up and complete the tweaks I'm sure we'd like to see that, but as-is this has been a draft for over a year with no updates in that time

**Pull request closed without merging**
