### PR TITLE
Implement PHP-CS-Fixer as an automated workflow

### PR DESCRIPTION
**Pull request by evrifaessa**
Implemented [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) as an automated workflow. It will automatically run on pull requests using our bot account, [fossbilling-bot](https://github.com/fossbilling-bot).

I've also tweaked some of the rules. Let me know if you think there's anything worth changing.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Personally prefer to use https://typicode.github.io/husky/#/

instead of automated bot committing to the PR

**Review by BelleNottelling — APPROVED** [review]
So ultimately this LGTM, however I don't know if the bot will be able to automatically commit the styling changes to forked branches for PRs.
I *think* it will be able to as long as they author didn't disable the "allow contributions from contributors" option, but I'm not entirely certain.

Ultimately, I'd like to hear what @admdly thinks as I know he's recently cleaned up our workflows and generally seems to have the most experience with them out of the team.

**Comment by John-S4** [comment]
> So ultimately this LGTM, however I don't know if the bot will be able to automatically commit the styling changes to forked branches for PRs. I _think_ it will be able to as long as they author didn't disable the "allow contributions from contributors" option, but I'm not entirely certain.

I'm pretty certain this is correct.  

> Ultimately, I'd like to hear what @admdly thinks as I know he's recently cleaned up our workflows and generally seems to have the most experience with them out of the team.

I'd agree with that, curious what @admdly thinks about this. 

Regarding @jaapmarcus point, I'm also not a huge fan of the idea of a bot potentially making commits to every PR, but as long as we are very certain and clear about the rules that it is using then I can see the sense in it.

**Comment by BelleNottelling** [comment]
Could we perhaps get a new PR that just introduces the new rules & runs it against the repo and then worry about the automation at a later date?

Those changes alone are quite good, and by getting the main branch formatted according to proposed rules here would help prevent this PR from slowly becoming more and more conflicted with the main branch.

**Comment by BelleNottelling** [comment]
I'm pushing this one through. The changes are good and I'm tired of it sitting here indefinitely when it can instead be merged and the project can finally have automated CS being performed.
I've also disabled codefactor's PHP support as it is imo at best, redundant with this + our other PHP CI workflows

**Pull request merged**
