### PR TITLE
Implementing the new extension store

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR implements the new backend written from scratch in [FOSSBilling/extension-store](https://extensions.fossbilling.org).

## The backend
The backend is a Next.js server with data currently fed statically in a file-based data store. I've kept the API responses identical as much as I could to the old extension store used in 2015 in BoxBilling.

The Next.js app also has some basic frontend done to it temporarily. I couldn't see any reason to prioritize its front end as the majority of the users probably will install their extensions on the admin panel, so I'm not going to work on it any further for some time.

This is an example of the data returned from the "list" API endpoint: https://extensions.fossbilling.org/api/list
You can also return the data of an individual module like so: https://extensions.fossbilling.org/api/extension/serviceproxmox

We can adjust the data here: https://github.com/FOSSBilling/extension-store/blob/main/utils/sample-data.ts

I'm pretty sure the backend will cover our needs until the catalogue grows to a bigger size, I'll consider handling the data in a better way then.

## Integrating it with the FOSSBilling admin panel
The admin panel already had the related layouts and the underlying routes ready, but they needed some overhaul. I've switched it to the ZIP toolkit we're using for our core updater, and from cURL to Guzzle.

I've also updated the tests accordingly, so this PR should be ready to be tested.

image

## How to test
- Go to your admin panel
- Extensions -> Overview
- Slide down
- Check the "Modules on the extension store" tab

## Plans for the future

- "Extension details" page inside the admin panel
- Properly writing the new front end for the store
- Version constraints, e.g. modules defining what version of FOSSBilling the module is tested for
- "Active installations" telemetry
- Keeping the old versions in a data store and archiving them

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by evrifaessa** [comment]
I'll deal with the tests. Seems like we aren't done yet.

**Comment by evrifaessa** [comment]
Alright. Tests are now refactored to use the Guzzle mock instead of cURL.

I've also removed tests related to the ZIP toolkit. In my opinion they should be done either by us in separate test cases or by the maintainer of the PHPZip package anyway.

Please squash and merge, I've done too many testing commits and wouldn't want to make the commit history a mess.

**Review by BelleNottelling — APPROVED** [review]
Tested and it works. I think we should do a separate tab for modules on the extension store, but  we can make more tweaks after merging this if needed

**Comment by John-S4** [comment]
Excellent work, thanks @evrifaessa

**Pull request merged**
