### PR TITLE
Introducing the FOSSBilling CLI

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR starts working on a basic console application made with Symfony's [console component](https://symfony.com/doc/current/components/console.html).

I've also added three commands to begin with:
* cache:clear
* cron:run
* system:version
* system:releasenotes
* theme:list

Keeping this as a draft while I'm still experimenting with it. Reviews and suggestions appreciated.

It's pretty easy to write commands. Modules now can have a `/Commands` subdirectory. I'll also update the example modules once this is merged.

The component also has great helpers for [tables](https://symfony.com/doc/current/components/console/helpers/table.html), [progress bars](https://symfony.com/doc/current/components/console/helpers/progressbar.html) and [asking for user information](https://symfony.com/doc/current/components/console/helpers/questionhelper.html).

image
image

### CODE REVIEW

**Comment by evrifaessa** [comment]
In the future, I might implement commands for modules. Modules would be able to define their own commands. Would be great for extensibility and maintainability.

**Comment by evrifaessa** [comment]
Here is how the tables look. They can also be tweaked to look different:

image

**Comment by BelleNottelling** [comment]
@evrifaessa any plans to get this to a mergeable state?

**Comment by ChristianGabs** [comment]
I think this is really old

Few suggestion
Rebuild the console.php

```php
<?php
if (php_sapi_name() !== 'cli') {
    die('This script can only be run from the command line.');
}

require_once __DIR__.'/load.php';
$di = include __DIR__.'/di.php';

$di['translate']();

$di->register(new \CristianG\PimpleConsole\ServiceProvider(), [
    /**
     * Set the console application name. Defaults to 'Console'
     * @param  string
     */
    'console.name'    => 'FossBilling Console Commands',
    /**
     * Set the console application version. Defaults to '1.0'
     * @param  string
     */
    'console.version' => $di['mod_service']('system')->getVersion(),
    /**
     * Set console application list
     * @param  array
     */
    'console.classes' => function ($di) {
        $modules = $di['mod']('extension')->getCoreModules();
        $fullyQualifiedClassName = [];
        // Dynamically load the commands from the modules
        foreach ($modules as $module) {
            $cap = ucfirst($module);
            $commands = glob(__DIR__.'/modules/'.$cap.'/Commands/*.php');
            foreach ($commands as $command) {
                $commandClass = basename($command, '.php');
                // Construct the fully qualified class name
                $fullyQualifiedClassName[] = "\\Box\\Mod\\$cap\\Commands\\$commandClass";
            }
        }
        return $fullyQualifiedClassName;
    },
    'console.allow_namespace' => true
]);

$console = $di['console'];

$console->run();
``` 

That will give ability to do 

```php
php console.php cron:run
```
or 

```php
php console.php --namespace="\Box\Mod\Cron\Commands\Run" cron:run
```

I will start review each command created as they are broken as well

image

**Review by admdly — APPROVED** [review]

**Comment by admdly** [comment]
I've updated this to fix any issues with `main`. I see no reason why this shouldn't be merged - it is an initial implementation, but serves as an excellent example going forward.

**Pull request merged**
