### PR TITLE
Merge Kb and Support modules

### PR DESCRIPTION
**Pull request by admdly**
Merge the `Kb` and `Support` modules as they contain related functionality.

The update patcher changes the `kb_*` table names, and generally handles migration maintaining existing settings (i.e. if the knowledge base module isn't installed or deactivate, it will remain disabled after update).

Beyond this, a general high level clean-up of the support UI and navigation has been performed, mainly related to copy.

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
I think basically all of the exceptions being thrown in this PR should probably just be `InformationExceptions`

Additionally, the install SQL needs to be updated to match these changes

**Comment by admdly** [comment]
> I think basically all of the exceptions being thrown in this PR should probably just be `InformationExceptions`

Done - let me know if there are any changes. 😄 

> 
> Additionally, the install SQL needs to be updated to match these changes.

Also done - I forgot we didn't use a DB migration based system 😔.

**Review by BelleNottelling — APPROVED** [review]
Looks okay to me, I think all of the potentially world ending things have been handled so we should be good to go 😄

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
I lied, I've found spots that still reference the KB module and need to be updated to reflect it no longer exists.

See:
- https://github.com/admdly/FOSSBilling/blob/feature/merge-support-kb-modules/src/themes/huraga/html/layout_default.html.twig#L268-L284
- https://github.com/admdly/FOSSBilling/blob/main/src/modules/Page/html_client/mod_page_sitemap.xml#L26-L35 
- https://github.com/admdly/FOSSBilling/blob/main/src/install/sql/content_test.sql#L165
- https://github.com/admdly/FOSSBilling/blob/main/src/install/sql/content.sql#L136

**Comment by admdly** [comment]
> I lied, I've found spots that still reference the KB module and need to be updated to reflect it no longer exists.

Well noticed - I've addressed those (and two others I found with a broader check 🥲 ).

**Review by BelleNottelling — APPROVED** [review]
We should be good now, thanks!

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]
Haven't done a live test but everything looks reasonable.

**Pull request merged**
