### PR TITLE
Refactor System Updater

### PR DESCRIPTION
**Pull request by admdly**
Refactor `Box/Update` to clean things up, merge related functionality, improve error checking, and move to `FOSSBilling` namespace. Also refactor `foss-update.php` into core class, `UpdatePatcher`.

Tested using Docker (Apache/PHP 8.0) and live install (OLS/PHP 8.1), and everything is working as expected for me with all tasks being run each time. Once any changes have been made and merged, I will backport this to 0.4.x for a 0.4.4 release as planned. 🙂

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Review by BelleNottelling — COMMENTED** [review]
Overall it LGTM.
Although, I am wondering if we at all need to be concerned about a change locking someone out of the admin panel, preventing them from completing a manual update?

**Comment by admdly** [comment]
> Overall it LGTM.
> 
> Although, I am wondering if we at all need to be concerned about a change locking someone out of the admin panel, preventing them from completing a manual update?

It is a potential possibility I considered with a manual update, however if they upload all the files manually they shouldn't be locked out completely (unless we change the database significantly or required config params, in which case we could perhaps handle it then?). 

One other possible solution is to include a hidden file in the download archive (such as `.update-incomplete`) that we then check for and run the patching if detected. But this adds a check on each load and do we want to go this far at this stage?

**Comment by BelleNottelling** [comment]
> in which case we could perhaps handle it then?

tbh, if we have some kind of significant change in the DB that sounds like a major pain to try and handle in some kind of "fallback" mode when the update hasn't been fully complete. For the config file it's generally not too bad, plus that's easy enough for someone to manually correct if they are locked out.

> One other possible solution is to include a hidden file in the download archive (such as `.update-incomplete`) that we then check for and run the patching if detected. But this adds a check on each load and do we want to go this far at this stage?

I don't think the check would be that bad to add, but also I think the likelihood of the hidden file never being uploaded to the server to begin is relatively high, so I'm not sure how effective that'll be.

I don't know how much we need to be concerned about it ever being an issue.. but I do think it's something we need to at least take into consideration.

**Comment by admdly** [comment]
@BelleNottelling agree on all points. 

Though, I think for a change in which the install is broken by an update without the patches being applied, rather than having some fallback mode, I would expect we would ensure these are run to reach a workable state. For example, by having index call the `UpdatePatcher` at least once. 

We could potentially do this now, by including say an `update.php` that runs the `UpdatePatcher` once (if it exists) and then is removed. That could eliminate the need for the manual patcher and config updater altogether, though we may need to leave the option there.

**Comment by BelleNottelling** [comment]
@admdly Either option seems fine with me.
Optionally, I suppose we could publish a gist with the co

**Comment by admdly** [comment]
> @admdly Either option seems fine with me.
> 
> Optionally, we could follow the 2nd option you mentioned, but do it slightly differently by publishing a gist with a PHP file that can be used to execute the patches if for whatever reason the first time failed / they get locked out during a manual update.
> 
> Edit: I accidentally commented before I finished writing out my thoughts

I think for this release, a gist may well be the best idea (not that I expect it to be needed). There is a fairly elegant way to handle this, but it is dependant on larger changes which I'm trying to avoid for back-porting purposes. I will commit to ensure this case is handled prior to any such breaking changes though!

**Pull request merged**
