### PR TITLE
Box_Exception: log a backtrace when debug enabled

### PR DESCRIPTION
**Pull request by BelleNottelling**
Should be helpful for debugging.
Example stacktrace:
```
[29-Oct-2022 06:51:48 UTC] An exception has been called. Stacktrace:
[29-Oct-2022 06:51:48 UTC] /bb-library/Box/Update.php:171 - __construct(Error!)
/bb-modules/Extension/Api/Admin.php:125 - performConfigUpdate()
/bb-library/Api/Handler.php:116 - update_config()
/bb-modules/Api/Controller/Client.php:181 - __call(extension_update_config, )
/bb-modules/Api/Controller/Client.php:90 - _apiCall(admin, extension_update_config, )
/bb-modules/Api/Controller/Client.php:66 - tryCall(admin, extension_update_config, )
NO_FILE:NO_LINE - get_method(, admin, extension, update_config)
/bb-library/Box/App.php:217 - invokeArgs(, )
/bb-library/Box/App.php:370 - executeShared(Box\Mod\Api\Controller\Client, get_method, )
/bb-library/Box/App.php:158 - processRequest()
/index.php:28 - run()
```

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Optionally, should we create new config options for this & also add an option for the length of the stacktrace?

**Comment by evrifaessa** [comment]
> Optionally, should we create new config options for this & also add an option for the length of the stacktrace?

Sure, I'm always in favour of more customization.

**Comment by BelleNottelling** [comment]
> > Optionally, should we create new config options for this & also add an option for the length of the stacktrace?
> 
> Sure, I'm always in favour of more customization.

Alright, I can do that tomorrow

**Comment by BelleNottelling** [comment]
I lied and did it now. PR should be ready for reviews

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
