### PR TITLE
Define the version for api.js on the login screen

### PR DESCRIPTION
**Pull request by BelleNottelling**
Should help resolve issues we had with the old API.js file being cached & not automatically being reloaded

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]
Idealy we should set it to random number when you are on the main / non release version

**Comment by BelleNottelling** [comment]
> Idealy we should set it to random number when you are on the main / non release version

Preview builds use the commit hash used associated with the build for it's version, so that should take care of that

**Comment by jaapmarcus** [comment]
> > Idealy we should set it to random number when you are on the main / non release version
> 
> Preview builds use the commit hash associated with the build for it's version, so that should take care of that

But not when you use git clone  and build it your self...

**Comment by BelleNottelling** [comment]
> > > Idealy we should set it to random number when you are on the main / non release version
> > 
> > 
> > Preview builds use the commit hash associated with the build for it's version, so that should take care of that
> 
> But not when you use git clone and build it your self...

If people are smart enough to build the software themselves, they should know how to clear cache.

**Review by John-S4 — APPROVED** [review]
Love it, anything that reduces the amount of issues raised because caches haven't been cleared is excellent IMO.

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
