### PR TITLE
Moved SolusVM and Centova Cast into their own repos.

### PR DESCRIPTION
**Pull request by evrifaessa**
They are now in [FOSSBilling/SolusVM](https://github.com/FOSSBilling/SolusVM) and [FOSSBilling/CentovaCast](https://github.com/FOSSBilling/CentovaCast).

### CODE REVIEW

**Review by BelleNottelling — APPROVED** [review]
This was part of the dependency injector?
Wow..

**Review by jaapmarcus — APPROVED** [review]
We should update SolusVM repo with the delete sql dumps

**Comment by evrifaessa** [comment]
IIRC it already had the SQL queries in the service’s `install` method.

**Comment by jaapmarcus** [comment]
👍🏼

**Pull request merged**
