### PR TITLE
new repo

### PR DESCRIPTION
**Pull request by mlgtcode**

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Review by John-S4 — COMMENTED** [review]
There hasn't been a FOSSB release yet has there?

So, anything calling /releases/latest will fail currently?

**Comment by mlgtcode** [comment]
> There hasn't been a FOSSB release yet has there?
> 
> So, anything calling /releases/latest will fail currently?

yes, it will. not sure if it is a good option, from a security pov to allow automated updates from the old repo.

**Comment by jaapmarcus** [comment]
Can't we add an fallback if fetching the last relaease fails. I don't want it pinging the Boxbilling repo anymore imo

**Comment by jaapmarcus** [comment]
> > Can't we add an fallback if fetching the last relaease fails. I don't want it pinging the Boxbilling repo anymore imo
> 
> The change will cause this result: Screenshot 2022-06-09 at 15-27-05 Extensions - Demo_1

Then It is fine

**Comment by John-S4** [comment]
That works for me.

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
