### PR TITLE
Fixed Password Reset handling 

### PR DESCRIPTION
**Pull request by Anuril**
Small Security Issue with the Error Message. 
I fixed it so the message is the same whether the E-Mail address exists or not. Needs PR in the locale Repo to be completely fixed.

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
I'd rather the message be
"A password reset confirmation email will be sent to you if we found an account with that email address"

**Comment by John-S4** [comment]
> I'd rather the message be "A password reset confirmation email will be sent to you if we found an account with that email address"

I'd agree that is a nicer message.

**Review by 4yx — CHANGES_REQUESTED** [review]
Wouldn't it be better if the exception message was removed altogether (have the "If an account matching the address provided was found, a password reset confirmation email has been sent." message shown regardless of whether an exception occured), rather than having the same message multiple times?

In addition to that, the messages are currently not completely identical (a dot is missing on the Exception instances, very small detail but a skilled attacker could notice this, which is exactly why I'm making the suggestion above).

**Comment by BelleNottelling** [comment]
> Wouldn't it be better if the exception message was removed altogether (have the "If an account matching the address provided was found, a password reset confirmation email has been sent." message shown regardless of whether an exception occured), rather than having the same message multiple times?

Yes, actually. Rather than throwing the exception the system can simply return `true` and fake success & the `testreset_passwordEmailNotFound` check can be removed or updated to verify that the password reset is returning true.

Additionally, @Anuril the staff password reset API endpoint has the same exception message that should be handled in the same way:
https://github.com/FOSSBilling/FOSSBilling/blob/main/src/modules/Staff/Api/Guest.php#L154

**Review by BelleNottelling — APPROVED** [review]

**Review by BelleNottelling — APPROVED** [review]

**Pull request merged**
