### PR TITLE
Correcting icon paths

### LINKED ISSUE #337: [Bug] images are non existant (in system settings
**Describe the bug**
404 on icons in bb-admin/system

**To Reproduce**
1. look at bb-admin/system

**Expected behavior**
the actual image and not alt

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: win 10 pro
 - Browser chrome

**Additional context**
none

### PR DESCRIPTION
**Pull request by BelleNottelling**
Looks like there are a lot of icon paths that are outdated and point to icons from the old theme (which no longer exist)
This PR is intended to correct those paths so they now point to existing icons.

Don't merge yet.
I'm still poking around to see if I can find more icons that are broken

Closes #337.

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]

**Comment by evrifaessa** [comment]
@BelleNottelling still working on this?

**Comment by BelleNottelling** [comment]
@evrifaessa It's still on my list, but I have someone visiting this week so I likely won't be working on it during that time

**Comment by John-S4** [comment]
I had a quick look through and can't see any icons that you have missed. I'm not saying there definitely aren't any, but there aren't any anywhere obvious. :)

**Comment by BelleNottelling** [comment]
Rebased. Feel free to review and merge whenever

**Comment by evrifaessa** [comment]
@BelleNottelling I think this PR reintroduces some files we've removed while dropping the Forum module.

image

**Review by evrifaessa — APPROVED** [review]
Should be fine after the forum files files are removed.

**Comment by BelleNottelling** [comment]
> Should be fine after the forum files files are removed.

Fixed. Thought I told git to drop those files on the rebase, but I guess not

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
