### PR TITLE
Fix boxbilling/boxbilling#1306

### PR DESCRIPTION
**Pull request by andpavlenko**
* Fix boxbilling/boxbilling#1306
* Fix admin theme mod_cron_settings.html.twig
* Improve some admin templates

### CODE REVIEW

**Comment by andpavlenko** [comment]
In old source code, new recurring invoices generated based on price saved in database while ordered.
If you need to change product price, invoice will be issues based on saved in order old value, but does't new product price.
Therefore for change product price you need manual change value in order config for each user.

In which case need this behavior?
With a large number of users, this is not possible!

**Comment by andpavlenko** [comment]
If PR ok, I'll fix tests later.

**Review by John-S4 — COMMENTED** [review]
Issue fix makes a lot of sense. 

Aesthetic changes are good, and the PDF fix is also good. 

Once it passes tests, it all seems good to me.

**Review by evrifaessa — APPROVED** [review]

**Comment by John-S4** [comment]
I'm willing to admit to being a little bit lost with this PR by now. 

It seems like a lot of the things in it have been superseded and fixed by other merges since this was created, but the original issue with the inability to change price - #1306 is still not resolved, is that right?

If that is the case then maybe we can just extract that part from this PR and see if the tests pass to merge that.

**Pull request closed without merging**
