### PR TITLE
Fix for user menu

### PR DESCRIPTION
**Pull request by xSido**
This should fix the drop down menu on user page from where you can log out.

### CODE REVIEW

**Comment by xSido** [comment]
aaaa

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
Don't know if we can create a general file to arrange such things and include in every page or we have to update every them first

**Comment by jaapmarcus** [comment]
Also anychanges that are made upstream might be lost if we update bootstrap once. We should considering building the theme file our self

**Comment by John-S4** [comment]
I would suggest merging this now because people keep reporting the issue and it would solve it for now. 

If future themes are going to be built using tailwind in place of bootstrap then it is not a long term issue, but in a mid-term we can buid a more cross-theme solution if needed, it would just be good to get a fix out there.  @jaapmarcus thoughts?

**Comment by jaapmarcus** [comment]
We need to update all the theme files and only one. And add at the bottom:

/* Fix for menu */
.nav-item:hover .dropdown-menu {display: block;}

For example if we ever need to update the theme files at least git can merge it

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
