### PR TITLE
Create a config migration function

### PR DESCRIPTION
**Pull request by BelleNottelling**
Migrates an old BB config to the new FOSSBilling config.
Tested locally & it does seem to work correctly

### CODE REVIEW

**Comment by evrifaessa** [comment]
can we also get tests written for this?

**Comment by BelleNottelling** [comment]
> can we also get tests written for this?

What do you have in mind?

**Comment by evrifaessa** [comment]
I don't know. I also don't really know if we should aim for the highest test coverage until Laravel is here, might just be a waste of time.

**Comment by BelleNottelling** [comment]
Yeah, I can't really think of how we can write a test for it, but as long as we add new values to this, it should work fine.
I tested it locally and it was able to upgrade a BB config to the current standard for FOSSBilling

**Review by evrifaessa — APPROVED** [review]
LGTM

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
