### PR TITLE
Starting to move away from jQuery in the installer

### PR DESCRIPTION
**Pull request by evrifaessa**
This PR is the first step to removing jQuery dependance from the installer.

In this PR, I've rewritten the helper functions in regular vanilla JavaScript. It still depends on jQuery because of the "Smart Wizard" thing. I'm planning to find a replacement for that written in vanilla JS or maybe even start writing it. One step at a time.

We don't need to use jQuery. The "[You Might Not Need jQuery](https://youmightnotneedjquery.com/)" website was a great resource and I'm planning to continue replacing jQuery with vanilla JS wherever I can.

There should be no expected behavioral changes with this. However, please check if you can find any irregularities before merging it.

### CODE REVIEW

**Comment by evrifaessa** [comment]
I’ll review the code tomorrow to see if there’s anything to improve. You can review it but please don’t merge.

**Comment by BelleNottelling** [comment]
I would love to see jQuery be replaced as much as possible, especially since a lot of it is still quite old. Let us know when this PR is complete and I'll review it

**Comment by BelleNottelling** [comment]
@evrifaessa can we merge this?

**Comment by evrifaessa** [comment]
> @evrifaessa can we merge this?

I'm afraid not yet.

**Pull request closed without merging**
