### PR TITLE
Mark as paid now adds funds if the Payment Provider is "Custom".

### PR DESCRIPTION
**Pull request by Anuril**
When you press the "Mark as paid" Button on the invoice, you can now enter a transaction id.

If the Payment gateway of the Invoice is "Custom" and it's enabled, the transaction ID will be used to add funds in the amount of the invoice to the customer.

Then, it will be marked as paid, just like with any other payment provider.
However, it won't mark the invoice as paid anymore if the payment provider isn't "Custom".

This button has not been touched since 9 Years, so I doubt this will have a high impact, but if you think the behaviour should be different then what it is, lmk.

### CODE REVIEW

**Comment by roshansys** [comment]
As I can see there is now way to add partial payment for an invoice and the  Mark as paid button add payment to the customer addFunds. The correct way should be. There has to be Add Payment Option with the following fields:

Date:
Transactin ID
Amount

After adding this  the transaction should get add transaction table and should be visible on invoice page.

Please suggest if that is correct way so that I can start coding on that part

**Review by roshansys — COMMENTED** [review]
sees working but the transaction should go to transaction table

**Comment by Anuril** [comment]
Had to rewrite / add quite a few things for this. Now the transaction gets handled like the other payment adapters.

**Review by BelleNottelling — COMMENTED** [review]
Overall this looks quite a bit better than the original version (not that I looked at it super in dept)
Great work!

Two minor things:
1. I've pushed a few minor changes to your branch. It was mostly styling, but I also added in the `trans` filter in a few locations you missed. We need to do our best to not introduce untranslatable strings into FOSSBilling :)
2. I feel like this functionality would be useful for all payment gateways, right? It's entirely possible that a transaction will go through and then not appear correctly inside of FOSSBilling which would be a valid use-case to need to mark an invoice as paid & set a transaction ID for it. The only potential gotcha is that it's also possible that transaction may have appeared in FOSSBilling and was just never considered complete. I'd love to hear your thoughts on this

**Comment by John-S4** [comment]
> 2\. I feel like this functionality would be useful for all payment gateways, right? It's entirely possible that a transaction will go through and then not appear correctly inside of FOSSBilling which would be a valid use-case to need to mark an invoice as paid & set a transaction ID for it. The only potential gotcha is that it's also possible that transaction may have appeared in FOSSBilling and was just never considered complete. I'd love to hear your thoughts on this

@BelleNottelling I was with you all the way up to the potential gotcha part and then you lost me a bit. Why would that be an issue, if the transaction has appeared in FOSSBilling but not been considered complete then the logic should be that adding a manual transaction ID should override it for that invoice surely? Or am I missing something - it's been a long day.

**Comment by Anuril** [comment]
The Mark as Paid functionality already worked for _all other gateways_. It was designed for exactly the use case @BelleNottelling described (Except you can't set a transaction ID with it, but you don't need to because the transaction was done by the paygateway)

**Review by jaapmarcus — APPROVED** [review]

**Comment by BelleNottelling** [comment]
> (Except you can't set a transaction ID with it, but you don't need to because the transaction was done by the paygateway)

This is assuming that the transaction does correctly appear inside of FOSSBilling, but with a regular payment gateway (so not the `custom` one) you'll never be using the mark as paid button unless something didn't behave correctly, making it rather likely that the transaction itself might not be inside of FOSSBilling. 

That's why I think it would be nice to have the option (not be forced to) to set the transaction ID regardless of the payment gateway (as if I am understanding it correctly, the transaction ID that's entered is only used if it's the `custom` payment gateway).

**Comment by Anuril** [comment]
> This is assuming that the transaction does correctly appear inside of FOSSBilling, but with a regular payment gateway (so not the `custom` one) 

What's happening is this: 
Pressing the mark as paid button will [just call markAsPaid in the service](https://github.com/FOSSBilling/FOSSBilling/blob/bf3c40719ec4b9cfcb75be2bafd5a4882b20fa9e/src/modules/Invoice/Api/Admin.php#L60C14-L60C14) and [every invoice item will be marked as paid.](https://github.com/FOSSBilling/FOSSBilling/blob/bf3c40719ec4b9cfcb75be2bafd5a4882b20fa9e/src/modules/Invoice/Service.php#L372C11-L372C11) 

The Function [markAsPaid of the InvoiceItem](https://github.com/FOSSBilling/FOSSBilling/blob/bf3c40719ec4b9cfcb75be2bafd5a4882b20fa9e/src/modules/Invoice/ServiceInvoiceItem.php#L31C21-L31C21)  will check if the item was already charged to the customer and if not, it will add a new Charge to the [balance of the client](https://github.com/FOSSBilling/FOSSBilling/blob/bf3c40719ec4b9cfcb75be2bafd5a4882b20fa9e/src/modules/Invoice/ServiceInvoiceItem.php#L245)

> you'll never be using the mark as paid button unless something didn't behave correctly, making it rather likely that the transaction itself might not be inside of FOSSBilling.

The button (as it exists now) assumes that the payment was added correctly to the clients balance, and just the "activation" and or charge didn't work. This is current behaviour. 

If this button is pressed with the "Custom" Payment Gateway, markAsPaid tries to detract funds from the client balance, that are not there, leading to an error. 

My code adds a check to [first add transactions and balance](https://github.com/FOSSBilling/FOSSBilling/blob/e73690b8a8fa832d8a1396482cd4d308634651e3/src/modules/Invoice/Api/Admin.php#L75C24-L75C24) to the client before marking the funds as paid, so this error doesn't happen.

What you are talking about is more complex as it requires analysis of the existing transactions to see what failed and fixing that. While I can see that being handy in case a payment gateway fails _before the funds get added to the client_, this isn't the PR that's going to fix it. I think adding the refund functionality will require logic that will enable what you are thinking about, and I'll defer that until that time.

**Comment by John-S4** [comment]
> What's happening is this...

This all makes sense to me, and I think this can be merged as is now. But, yes, it will need to be revisited in the future to address the kind of issue that Belle is talking about and refunds.

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
