### PR TITLE
🎨 Maintenance page renovation

### PR DESCRIPTION
**Pull request by guillaumearnx**
updated the maintenance page to make it a little more tide-like in theme.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
I don't think we should mix themes and for main source code it should be closer to the default theme ...

**Comment by guillaumearnx** [comment]
> Member

yeah I agree. But for the maintenance page, the tide theme is very very similar to the default theme.

**Comment by BelleNottelling** [comment]
Your description makes it sound like this was taken directly from the Tide templates, but Tide doesn't have a template for the maintenance page.

> yeah I agree. But for the maintenance page, the tide theme is very very similar to the default theme.

I agree with Jaap. If we are going to make changes to a default template, it should be kept similar to the existing templates.
In what way is this one "Tide-like" other than using established Bootstrap classes VS some simple hard-coded classes?

Can you please share screenshots when proposing front-end changes?
Thank you

**Comment by guillaumearnx** [comment]
I simply mentioned Tide theme because I use the same layout / core page as the theme for the maintenance page. Indeed, these are just bootstrap classes. No directly link with Tide.
Here are some screenshots

image

**Review by BelleNottelling — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
