### PR TITLE
Update Stripe to the latest SDK

### PR DESCRIPTION
**Pull request by BelleNottelling**
Original upgrade / cleanup work to the HTML form aspect was done by @evrifaessa 
I finalized the work for it, fixed up a few bugs, made a few modifications to the code quality, and added an additional check to verify the transaction status before marking it as paid. Based on my testing, it should be ready for reviews and merging

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Tested, appears to be working.
image
Including 3D secure auth
image

And fails when it should:
image
image

**Comment by John-S4** [comment]
It seems to be working fine for me with Stripe test card numbers. I will circle back to it later on today and test a bit more thoroughly.

**Review by John-S4 — APPROVED** [review]

**Comment by John-S4** [comment]
I've tested a bit more thoroughly and it all seems good to me. 

If anyone else with a Stripe account could give it a quick test then it would be good, but personally I'm happy for it to be merged.

**Comment by jaapmarcus** [comment]
I am getting the error

strncasecmp(): Argument #1 ($string1) must be of type string, null given

**Comment by jaapmarcus** [comment]
If you are not logged in it is triggered...

Also when I refresh the url an payment is triggered again and added as credit to the account

**Comment by BelleNottelling** [comment]
@jaapmarcus I think something is wrong with your FOSSBilling instance, that error seems to be unrelated to these changes.

And after the last commit, it shouldn't be applying credit unless the transaction has actually completed, so if you can verify you have the most recent version of this PR and then provide more info on what you're doing to replicate that, I'd appreciate it.

**Comment by jaapmarcus** [comment]
> @jaapmarcus I think something is wrong with your FOSSBilling instance, that error seems to be unrelated to these changes.
> 
> And after the last commit, it shouldn't be applying credit unless the transaction has actually completed, so if you can verify you have the most recent version of this PR and then provide more info on what you're doing to replicate that, I'd appreciate it.

I am logged in as admin and as user on the same browser it looks fine it look like that the check.

**Comment by jaapmarcus** [comment]
> @jaapmarcus I think something is wrong with your FOSSBilling instance, that error seems to be unrelated to these changes.
> 
> And after the last commit, it shouldn't be applying credit unless the transaction has actually completed, so if you can verify you have the most recent version of this PR and then provide more info on what you're doing to replicate that, I'd appreciate it.

I am able to enter:

box.xxxx.nu/ipn.php?bb_gateway_id=9&bb_invoice_id=17&bb_redirect=true&bb_invoice_hash=d5cf4f5e5350c01727a62d8fc89e2895f603de62cfa8c21dd3c6f40a172a2b6a&payment_intent=pi_3MSOd1KMbFLlZMas1KxwtKF9&payment_intent_client_secret=pi_3MSOd1KMbFLlZMas1KxwtKF9_secret_Gj0e6Wup8Ax11lxUwEiNZGwf9&redirect_status=succeeded

And it will add invoice price to my account credits.  We should check if the payment allready exists and if it does ignore it

**Comment by jaapmarcus** [comment]
https://user-images.githubusercontent.com/9754650/213784012-7848c02e-09f7-447f-95eb-d9423adfb922.mov

See screen capture I made

**Comment by BelleNottelling** [comment]
> > @jaapmarcus I think something is wrong with your FOSSBilling instance, that error seems to be unrelated to these changes.
> > And after the last commit, it shouldn't be applying credit unless the transaction has actually completed, so if you can verify you have the most recent version of this PR and then provide more info on what you're doing to replicate that, I'd appreciate it.
> 
> I am able to enter:
> 
> box.xxxx.nu/ipn.php?bb_gateway_id=9&bb_invoice_id=17&bb_redirect=true&bb_invoice_hash=d5cf4f5e5350c01727a62d8fc89e2895f603de62cfa8c21dd3c6f40a172a2b6a&payment_intent=pi_3MSOd1KMbFLlZMas1KxwtKF9&payment_intent_client_secret=pi_3MSOd1KMbFLlZMas1KxwtKF9_secret_Gj0e6Wup8Ax11lxUwEiNZGwf9&redirect_status=succeeded
> 
> And it will add invoice price to my account credits. We should check if the payment allready exists and if it does ignore it
> 
> Also if I add the issue will not cause earlier error message.
> 
> ```
> if(is_null($url)){ $url='';}
> ```

Fixed

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
