### PR TITLE
Fixed star history link in README

### PR DESCRIPTION
**Pull request by evrifaessa**

### CODE REVIEW

**Review by HunterNyan — APPROVED** [review]
Is Good, 10/10 review, will ask for help again XD

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Don't we need to include an api key due to the rate limit?

**Comment by evrifaessa** [comment]
> Don't we need to include an api key due to the rate limit?

Do we?

**Comment by jaapmarcus** [comment]
It looks like Github is exclude from ratelimts the Github api has ...

**Pull request merged**
