### PR TITLE
Use Rector to modernize code for PHP 8.0

### PR DESCRIPTION
**Pull request by BelleNottelling**
As the tin says, uses [Rector](https://github.com/rectorphp/rector) to "upgrade" (modernize) the code for PHP 8.0.
Most changes are pretty minimal, it's mostly replacing functions like `substr`, `get_class`, and `strpos` with newer functions that are cleaner to read in the code & therefore make it more obvious what it's doing

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — COMMENTED** [review]
Overall LGTM. But do we really need to import it as a dependency? Are we planning to run it again in the future?

**Comment by BelleNottelling** [comment]
> Overall LGTM. But do we really need to import it as a dependency? Are we planning to run it again in the future?

It has a lot of different filtering options that can be used, I will almost certainly go through some of the main ones and use at least a few of them

**Comment by BelleNottelling** [comment]
> Overall LGTM. But do we really need to import it as a dependency? Are we planning to run it again in the future?

Removed it, I can easily install it locally when doing the work

**Comment by jaapmarcus** [comment]
> Overall LGTM. But do we really need to import it as a dependency? Are we planning to run it again in the future

If for dev only and we are going to use it I don't see any reason why not to add it..  It is not included in the release anyway then...

**Comment by BelleNottelling** [comment]
Plus, when we decide to bump the minimum PHP version for the project, we can easily run it again to have it automatically upgrade things to the latest functions with that new PHP version.

It's actually pretty handy, especially because we can't properly keep track of every new feature PHP implements and then update the code to use it

**Comment by evrifaessa** [comment]
> If for dev only and we are going to use it I don't see any reason why not to add it.. It is not included in the release anyway then...

Yup, makes sense.

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
