### PR TITLE
Change storage engine to InnoDB

### PR DESCRIPTION
**Pull request by andpavlenko**
Issue #78 - Change database store engine MyISAM to InnoDB. No any impact working projects.

### CODE REVIEW

**Comment by andpavlenko** [comment]
> This sort of change needs to be applied to all tables, see the update file.

Don't understand. Point to file or more details?

**Comment by HunterNyan** [comment]
Sorry was on my phone.
The update script is: https://github.com/FOSSBilling/FOSSBilling/blob/main/src/bb-update.php where there's tables being created in it. 

For the sake of consistency, we should ensure that all the tables created by the project should be using the same engine, and preferably the modules which have SQL inside get updated as well.

**Comment by andpavlenko** [comment]
> The update script is:

But community decided don't care about compatibility with BB and write migration to Laravel. What's sense write migration with outdated script?

> modules which have SQL

I don't find create tables inside modules.

**Comment by John-S4** [comment]
If that covers all of the modules then just make the changes as well in the update script, for the sake of consistency whether that script will be around for long or not, and then I do not see any reason that this can not be merged.

**Comment by andpavlenko** [comment]
1247236 Something else?

**Comment by andpavlenko** [comment]
[c528935](https://github.com/FOSSBilling/FOSSBilling/pull/80/commits/c528935419ae11e2f0437b40233bd80d317589bc) - This is outddated config. New in root directory.

**Review by John-S4 — APPROVED** [review]
I can't find any missed tables, so all seems good to me.

**Review by evrifaessa — APPROVED** [review]

**Comment by HunterNyan** [comment]
Looking pretty good, I'll test it tonight :D thanks @andpavlenko

**Pull request merged**
