### PR TITLE
Use product price for reoccurring payments

### PR DESCRIPTION
**Pull request by BelleNottelling**
This change is cherrypicked from https://github.com/FOSSBilling/FOSSBilling/pull/113 and should close out https://github.com/boxbilling/boxbilling/issues/1306

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
we should fix the test first..

**Review by evrifaessa — APPROVED** [review]
Should be good once tests pass.

**Review by John-S4 — APPROVED** [review]
Works for me, merge it when that annoying test is resolved. :)

**Comment by DataLores** [comment]
Has the community weighed in more broadly on the impact of this change?

While I understand the intent of this change, it does have side-effects. For one, many customers may have recurring subscriptions setup via PayPal for a given invoice series. If the price of the product cannot change independent of previous orders, than this may invalidate existing subscriptions and cause customers to default on their account balances, requiring cancel/re-setup of the subscription.

It seems like this should be a configurable mode rather than the accepted default.

**Comment by John-S4** [comment]
This draft PR is about a year old with the last comment posted in January. 

Everything has moved on a lot since then, how relevant is this still, and if it is not then can we close it.

**Comment by admdly** [comment]
Agree with @John-S4 about this likely now being severely outdated with the number of changes, and also with @DataLores about the potential impact of this change. 

Updating the product price for existing services should be an action taken manualy and after careful consideration - perhaps in the future a bulk update option or configurable setting for this could be added? However, in the current form I'd be concerned about implementing this change.

**Review by admdly — CHANGES_REQUESTED** [review]
We should reconsider whether it is a good idea to automatically pull the latest price - it is likely to cause more problems than it's worth.

**Comment by John-S4** [comment]
> Updating the product price for existing services should be an action taken manualy and after careful consideration - perhaps in the future a bulk update option or configurable setting for this could be added? However, in the current form I'd be concerned about implementing this change.

This actually makes a lot of sense to me.

**Pull request closed without merging**
