### PR TITLE
Update NPM lock file to resolve apexcharts dependency issue

### PR DESCRIPTION
**Pull request by admdly**

### CODE REVIEW

**Comment by BelleNottelling** [comment]
I do believe the issue is fully with renovate itself. If you look at the git history, I had already upgraded the majority of the NPM packages and refreshed the lock file

**Comment by admdly** [comment]
> I do believe the issue is fully with renovate itself. If you look at the git history, I had already upgraded the majority of the NPM packages and refreshed the lock file

You're absolutely right; renovate occasionally gets into this state. Usually it can be coerced back into a 'good' state.

**Comment by BelleNottelling** [comment]
> > I do believe the issue is fully with renovate itself. If you look at the git history, I had already upgraded the majority of the NPM packages and refreshed the lock file
> 
> You're absolutely right; renovate occasionally gets into this state. Usually it can be coerced back into a 'good' state.

Still borked, lol
image

**Comment by admdly** [comment]
> > > I do believe the issue is fully with renovate itself. If you look at the git history, I had already upgraded the majority of the NPM packages and refreshed the lock file
> > 
> > 
> > You're absolutely right; renovate occasionally gets into this state. Usually it can be coerced back into a 'good' state.
> 
> Still borked, lol image

Indeed - usually in these cases it resolves with the next version bump. 🤷‍♂️

**Pull request merged**
