### PR TITLE
Remove remaining Google Fonts

### LINKED ISSUE #249: Replace Google Fonts
_(a part of #176)_

We rely on Google Fonts in [12 different files](https://github.com/FOSSBilling/FOSSBilling/search?q=fonts.googleapis.com). We should replace them.

### 2. Downtimes potentionally breaking the software
Our software should be able to continue functioning regularly if Google Fonts has a downtime. Keeping these fonts locally or replacing them with [web-safe fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp) should minimize the impact on our users.
### 3. GDPR
Even if the user isn't practically visiting a website owned by Google, the resource is hosted on Google's servers and they do log identifying information about the user. A regional court in Munich, Germany recently had a judgement about Google Fonts. To read more on this, [here is a link](https://www.lexology.com/library/detail.aspx?g=8546d90b-61f5-4c96-8bd0-86d1676863c2).

## How to replace
For some (many) instances, we can replace the fonts with [web-safe fonts](https://www.w3schools.com/cssref/css_websafe_fonts.asp). For other specific fonts, there are useful tools like [this](https://google-webfonts-helper.herokuapp.com/fonts) to grab the source and self-host.

### PR DESCRIPTION
**Pull request by admdly**
Replaces remaining Google fonts with web safe fonts (resolves #249, part of #176).

Note that I've also removed the fb_wallet.svg background image from the exception/error page as this is hardcoded HTML which shouldn't rely on external resources (especially an external theme file). Let me know if you'd prefer this be left.

### CODE REVIEW

**Comment by John-S4** [comment]
I agree that the logo image should not be loaded from a theme file - that really doesn't make much sense at all.

But I also think that it makes for a much nicer looking error page to have the logo on there and I don't think that just deleting it completely is the way to go.

**Comment by admdly** [comment]
@John-S4 There is still a background, through agreed not as nice. 

Given the image in question is SVG and the page is statically defined in the code right now anyway, I could simply embed it within the HTML until a more permanent solution (such as breaking it out into it's own HTML file) is found?

**Comment by John-S4** [comment]
> Given the image in question is SVG and the page is statically defined in the code right now anyway, I could simply embed it within the HTML until a more permanent solution (such as breaking it out into its own HTML file) is found?

That sounds like a much better plan to me than just removing it completely.

**Review by jaapmarcus — APPROVED** [review]

**Comment by admdly** [comment]
@John-S4 I've pushed a change to embed the background image inline.

**Review by BelleNottelling — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
