### PR TITLE
Fix #665 and #631 where input name=field[] is used

### LINKED ISSUE #665: [Bug] Custom product upgrades are not saved
**Describe the bug**
I have 2 custom products (VM and Custom VM). the general idea is that if the client needs more to use the upgrade option for the custom VM product (where i have addon defined althought they can only take one quantity of addon)

When i Update the product page i mark the product which is a available update, looks saved but when i return it seems it's not save (this can be connected to the JSON issue which awas resolved with the latest release)

**Expected behavior**
Saving of Upgrades needs to work.

**Screenshots**
https://prnt.sc/MDfXoiRC_QKl
https://prnt.sc/4LX1XzUOHyAq

**Additional context**
Now sure if Custom products are the right way if we do not need to provision the VM (as using some plugin for VM since we provision Vmware manualy)

### PR DESCRIPTION
**Pull request by jaapmarcus**
Object.formEnteries only return the last "value" when fieldname[] is used this behavoir is incorrect and this PR restores the behavoir by converting them to a array. After that reformatJSON should take care of it.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Replaces both https://github.com/FOSSBilling/FOSSBilling/pull/682 and 
https://github.com/FOSSBilling/FOSSBilling/pull/668

Returns:
`{"CSRFToken":"1521b6d3a6373226deea900b636d84fb","config":{"server_id":"","hosting_plan_id":"","reseller":"0","free_domain":"1","free_tlds":[".com",".net",".nl"],"free_domain_periods":["1M","3M","6M","1Y","2Y","3Y"],"free_transfer":"1"},"id":"6"`}

Instead the old 

`{"CSRFToken":"1521b6d3a6373226deea900b636d84fb","config":{"server_id":"","hosting_plan_id":"","reseller":"0","free_domain":"1","free_tlds[]":"nl""free_domain_periods":"3Y,"free_transfer":"1"},"id":"6"}`

**Review by BelleNottelling — APPROVED** [review]

**Comment by BelleNottelling** [comment]
What about the client area?

**Comment by jaapmarcus** [comment]
I don't see any update by @evrifaessa  regarding the first PR https://github.com/FOSSBilling/FOSSBilling/commits/main/src/themes/huraga

**Comment by evrifaessa** [comment]
Yeah, Huraga is stil using the existing jQuery solution.

**Review by evrifaessa — APPROVED** [review]
Haven't really tested, but can't see any problems.

**Pull request merged**
