### PR TITLE
Fix: #640 replace whois script with external library

### LINKED ISSUE #640: Error searching domain [Bug]
When I go to search for a domain to buy, all domains are showing as available for purchase, example: google.com
I'm using the email registrar domain, because I'm putting .br domains for resale.
And it doesn't have a registrar like resellerclub for Brazil.

https://www.whoisxmlapi.com/

I use it to validate domains in another script and it is working normally.

Thank You
Heber Queiroz

### PR DESCRIPTION
**Pull request by jaapmarcus**
Fixes #640

As explained in #653 our existing whois server "database" is hopeless outdated and updating to a more current level will take more time then I want to invest in the 2 adapters that ideally should never been used. 

Replaces Whois2 and Whois class with https://github.com/io-developer/php-whois

### CODE REVIEW

**Review by BelleNottelling — APPROVED** [review]
LGTM
Thanks!

**Review by evrifaessa — APPROVED** [review]
LGTM.

**Comment by heberq1978** [comment]
Hello, since the update now the error is being another, it is showing the following error after performing the search:
Network is unreachable
My installation is at:
https://financeiro.hospedarsite.net.br/order
If you want to test, feel free, if necessary I'll create an account just for this purpose.
Thank's

**Comment by jaapmarcus** [comment]
Please check

https://github.com/io-developer/php-whois#installation

Make sure port 43 is open in the firewall

**Pull request merged**
