### PR TITLE
Fix Email Template Preview

### PR DESCRIPTION
**Pull request by Stage4000**
I originally made the text black but then after seeing that the emails set the font color at #333333 in CSS I decided to copy that.

### CODE REVIEW

**Comment by BelleNottelling** [comment]
I think really what we need to do is replace that with something else where the email content isn't influenced by the existing CSS on the page as otherwise the preview won't truly render correctly.

I'm far from a frontend expert, but I think a shadow dom accomplishes that task need?
I don't really know, I just know it should be possible to do it better than what we have now

**Comment by Stage4000** [comment]
I agree, but this at least works short term until someone with far more skill than me can fix it for real.

**Comment by Stage4000** [comment]
I am def not smart enough to figure this one out, but if someone understands what I'm saying and knows WHERE to implement it then please do so:


We could fully render the template (including CSS) using an iframe and some JS. Example JS function for writing to the iframe included below.

```
function renderTemplate(content) {
            const iframe = document.getElementById('preview');
            const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
            iframeDoc.open();
            iframeDoc.write(content);
            iframeDoc.close();
        }
```

**Comment by Stage4000** [comment]
There very well could be a better way to do it, but this seems the simplest.

**Pull request closed without merging**
