### PR TITLE
Namecheap adapter

### PR DESCRIPTION
**Pull request by ashavolian**
Requirements:
Install XML on your server before using.

Details:
There are two files in this PR.
The first is `Namecheap.php` which provides support for registering/transfer of domain names through the Namecheap API.

The second is essentially a copy of the first, but with added support for Auto-config of nameserver using ClouDns Master Zones.

Bug reports:
The `setPrivacy` functions throw appropriate errors but they do not appear in the fossbilling UI.
Fossbilling UI always shows a success message when changing privacy setting on a domain. This is a Fossbilling src bug and I couldn't fix it from the scope of my adapter.

Namecheap API does not support EPP code retrieval. So transfering out of Namecheap is not supported.

There are a few contact fields that should be added to Fossbilling settings to comply which certain country TLD's. For example, only canadian companies/citizens can purchase .ca domains.

### CODE REVIEW

**Comment by John-S4** [comment]
Is there some realationship between Namecheap and ClouDNS that I'm missing, or is that just something that fits your personal use case?

**Comment by jaapmarcus** [comment]
It looks like there are 2 different identities. 

https://www.similartech.com/compare/cloudns-vs-namecheap-dns

It would be nice if we can add support for 3rd party DNS on all registars but it probally becomes a huge drama.

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
You need to add something along these lines for this to work correctly:
Otherwise this entirely breaks the admin panel

    public function isDomaincanBeTransferred(Registrar_Domain $domain){
        throw new Registrar_Exception("isDomaincanBeTransferred is unsupported with the Namecheap adapter");
    }

**Comment by John-S4** [comment]
> It would be nice if we can add support for 3rd party DNS on all registars but it probally becomes a huge drama.

It would be very nice.

**Review by jaapmarcus — APPROVED** [review]

**Review by BelleNottelling — APPROVED** [review]
I've rebased this, fixed the issue I described, removed the clouDns one since we agree it doesn't belong in the core software, and removed the srsx adapter since it's a broken mess

**Review by evrifaessa — APPROVED** [review]
~Should be good once tests pass~
Seems like they only are CodeFactor failures which were triggered by the TODO keyword. LGTM.

**Comment by evrifaessa** [comment]
Thanks for the great contribution. We really appreciate it. ❤️

If you want to have direct contact with the team, we would be very glad if you [joined our Discord server](https://fossbilling.org/discord).

**Pull request merged**
