### PR TITLE
Make the option to update assigned server ip addresses visible

### PR DESCRIPTION
**Pull request by jaapmarcus**
Same as in "Add new server"

### CODE REVIEW

**Comment by John-S4** [comment]
This might be a dumb question and maybe I'm missing something, but why was this commented out and disabled in the first place - how has whatever that reason was changed now?

**Comment by jaapmarcus** [comment]
I don't know we should ask Fordnox about it

**Comment by BelleNottelling** [comment]
> I don't know we should ask Fordnox about it

I highly doubt that he'd answer that question. Anyways, as long as you've tried saving the updated IP addresses and verified it saves correctly, I'll approve this

**Comment by jaapmarcus** [comment]
I have tested and it works...

**Review by BelleNottelling — APPROVED** [review]

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
