### PR TITLE
Set the default currency during installation

### PR DESCRIPTION
**Pull request by BelleNottelling**
With this change, we should help prevent issues with people deleting the default currency after installation because they aren't wanting to use USD. Tested and verified to install correctly with these changes.
image

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by evrifaessa** [comment]
I have a feeling this breaks the installer script we use with Docker.

**Comment by BelleNottelling** [comment]
> I have a feeling this breaks the installer script we use with Docker.

Is there any reason why we don't just have the user run through a mostly standard install with docker?

**Comment by evrifaessa** [comment]
> > I have a feeling this breaks the installer script we use with Docker.
> 
> Is there any reason why we don't just have the user run through a mostly standard install with docker?

It does an unattended install using the installer script. If possible, I’d much rather leave the related part in the content dump, then update the value after the dump is imported.

This way, we would both keep the old functionality and allow the customization wanted to achieve in this PR.

**Comment by evrifaessa** [comment]
Another option would be getting the unattended preparation script to set it to USD, but I would prefer the PR to implement that before we merge it.

**Comment by BelleNottelling** [comment]
> Another option would be getting the unattended preparation script to set it to USD, but I would prefer the PR to implement that before we merge it.

But that leaves the same issue for the docker image with people deleting the USD currency and things breaking. 
I tried to reproduce the issue reported by creating a product, setting a price, and then deleting the default currency, but nothing broke for me. So this is the closest to fixing the issue that I can get at this very moment

**Review by evrifaessa — APPROVED** [review]
Thanks for the PR and the quick changes afterwards. It looks good to me and I'm happy we finally will get some more customization in the installer.

In the future, I'm planning to implement other crucial settings like the company name into the installer.

**Pull request merged**
