### PR TITLE
Delete changelog.md and tweak cspell.json

### PR DESCRIPTION
**Pull request by BelleNottelling**
This deletes the change log from this repo in favor of the one on our website, so we don't have to maintain two.
I also made an update to the cspell,json file so we can get spell check coverage in the ``mod_system_settings.html.twig`` file.

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]

**Comment by John-S4** [comment]
Sorry if I'm being a bit dense, but what is this list of 'always correct' words for?

Because some of them are pretty unusual. At least a few of them might also be considered common misspellings or typos for more commonly used words.

**Comment by BelleNottelling** [comment]
> Sorry if I'm being a bit dense, but what is this list of 'always correct' words for?
> 
> Because some of them are pretty unusual. At least a few of them might also be considered common misspellings or typos for more commonly used words. 

Both lists effectively are just ignore lists, for the most part they are names or words from the code that cspell flagged as an invalid word, so I add it to the list so that there's not tons of stuff to sort through when doing the spell check. It's not impossible that I've whitelisted actual typos, though. Feel free to point out specific ones and I'll check it

**Comment by John-S4** [comment]
Also you have 'Sint' listed twice in the ignore list.

**Comment by jaapmarcus** [comment]
I would prefer have a change log in the repo and link from the website to here..

**Comment by John-S4** [comment]
And 'proccess' is a wrong spelling but is in the ignore list for some reason.

**Comment by evrifaessa** [comment]
I'd prefer having it in our website much more.

- Our website is a React-based website, allowing us to customize the look much more. It might not be needed for now, but I'd love to create better-looking collapsibles for legacy releases when the list gets longer.
- You need 2 approvals to merge **anything** to the main repo. It doesn't make much sense to wait for 2 approvals after doing a release just to update the changelog. Might not be that much of a waiting time, but there's just no reason to wait for it while you can just have it in the website and can link it from here.

**Comment by evrifaessa** [comment]
> If waiting 2 approvals is to much for a release why do we brother it with it at all...

No, we are not waiting 2 approvals for the release. We are waiting just for the changelog. You don't need to do additional commits before making any releases, you just take the main branch and change the version string, that's all. But right now, the only thing you need to do it commiting the changelog and I don't think we need to do that.

**Comment by evrifaessa** [comment]
> If somebody forks the project it is useful to see the changes have been made in the repo than on a website

Well as far as we know, the project isn't going anywhere in the foreseeable future.

The website also is completely [open-sourced](https://github.com/FOSSBilling/FOSSBilling), so even if it goes down for some reason, the source of everything is still there.

**Comment by jaapmarcus** [comment]
> > If waiting 2 approvals is to much for a release why do we brother it with it at all...
> 
> No, we are not waiting 2 approvals for the release. We are waiting just for the changelog. You don't need to do additional commits before making any releases, you just take the main branch and change the version string, that's all. But right now, the only thing you need to do it commiting the Changelog and I don't think we need to do that.

Because Github does not support any kind of protection for drafting releases any admin can do it. But it doesn't mean at least we should implement such validation just prevent issues we had with 0.2.0 and on... 

Changelog applies to the repo and please keep changelog and repo together. No body gives a *** about a good looking website and if we we want in the future we can just run file_gets_contents(../CHANGELOG.MD) instead including it from a remote source.

**Comment by BelleNottelling** [comment]
> Changelog applies to the repo and please keep changelog and repo together. No body gives a *** about a good looking website and if we we want in the future we can just run file_gets_contents(../CHANGELOG.MD) instead including it from a remote source.

Nobody even updates the changelog on the repo. It was almost completely ignored back with BoxBilling and it still goes mostly ignored here with FOSSBilling. Same with the website's changelog, too, but I can easily update that when needed since it doesn't have to go through 2 approvals before merging the PR



> In that case I think they are probably all fine. 'Sint' is my biggest concern, since 'Saint' will also be commonly used for country names as well.

Sint is the name of a place. See:

https://github.com/FOSSBilling/FOSSBilling/blob/59027f6535c2e77a8ed4076e654a160508874ecf/src/modules/System/Service.php#L920
https://en.wikipedia.org/wiki/Sint_Maarten

**Comment by John-S4** [comment]
> Sint is the name of a place. See:

Yep, I know where Sint Maarten is, my point was that there are also lots of countries with 'Saint' in the name, so adding it to an ignore list will also ignore any misspellings of those, no?

Also, it's there twice in the list in cspell.json on lines 37 and 50, is that intentional?

**Comment by John-S4** [comment]
> I would prefer have a change log in the repo and link from the website to here..

That would also generally be what I prefer, I just somehow expect to find the changelog on GH rather than needing to go looking somewhere else. I genuinely don't know what the best solution is.

**Comment by 4yx** [comment]
You could link the changelog of the website to this repo.
One would be [to use a submodule and link the file](https://github.com/4yx/FOSSBilling/tree/submodule), but that would just copy the entire website when someone clones the repo, and would be quite useless.

Theoretically, GitHub Actions can also be used to copy the file over to this repo, the only problem I'm thinking of is how to set up the trigger, I don't know if Actions can support checking the state of a file in another repository and triggering only when it's updated (it can also work without that, but the job will fail if the contents are the same).

**Comment by jaapmarcus** [comment]
With the release drafter we should be able to update the changelog automatically and make an exception for it so it doesn't require a PR request. 

Doing it manually is always a bad idea

**Pull request closed without merging**
