### PR TITLE
Improvement remove unused things

### PR DESCRIPTION
**Pull request by jaapmarcus**

### CODE REVIEW

**Comment by BelleNottelling** [comment]
If anyone has these registrars enabled, deleting them will lead to a broken installation..

**Comment by jaapmarcus** [comment]
> If anyone has these registrars enabled, deleting them will lead to a broken installation..

It is using the resellerclub api that was broken for a few months... 

So I don't think they would be used. 

Or we could  change the registrar in tld_registrar to ResellerClub they are using the same api . Only with different branding

**Comment by BelleNottelling** [comment]
> > If anyone has these registrars enabled, deleting them will lead to a broken installation..
> 
> It is using the resellerclub api that was broken for a few months...
> 
> So I don't think they would be used.
> 
> Or we could change the registrar in tld_registrar to ResellerClub they are using the same api . Only with different branding

I'd be really nice to have telemetry right now, we'd be able to see if people for example held back without updating because it broke / see if anyone actually used the variations that extended the ResellerClub integration.

**Comment by BelleNottelling** [comment]
`GetTlds` is gone, so that portion of this PR is complete.

I agree that the registrars that just extend Resellersclub are a bit of a sore thumb, but I still hold the opinion we should make the removal of them clean for existing installations & ensure that people won't find that their system unexpectedly bricks itself

**Pull request closed without merging**
