### PR TITLE
Drop the BB prefix 

### PR DESCRIPTION
**Pull request by BelleNottelling**
This PR renames and removes the BB prefix from folders and files in the root src dir.
It also drops the BB_ prefix for the path variables, but does keep an alias for the moment.

If the system detects an old folder, it'll display a message instructing the user to migrate any custom files to the new folder and delete it

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Last commit adds this message which will be helpful for people who currently have an installation. I will do more cleanup / renames in a different PR, this one is already cluttered.
image

**Review by evrifaessa — APPROVED** [review]
If you've tested it, LGTM. Great PR.

**Comment by John-S4** [comment]
Looks good, trying to skim through the changes and can't see anything worrying, but wow that's a log of changed files 😁 

Very good call on the 'error' message.

**Comment by jaapmarcus** [comment]
2 Merge conflicts
src/bb-modules/Orderbutton/html_client/mod_orderbutton_product_configuration.html.twig
src/bb-modules/Servicedomain/html_client/mod_servicedomain_order_form.html.twig

**Comment by evrifaessa** [comment]
Just tried installing from the branch. It all seems fine to me.

**Review by John-S4 — APPROVED** [review]
:)

**Pull request merged**
