### PR TITLE
Add support GTM for client bootstrap theme

### PR DESCRIPTION
**Pull request by andpavlenko**
Issue #84 GTM useful for connect analytics without hack the template code.

### CODE REVIEW

**Comment by andpavlenko** [comment]
Screenshot from 2022-05-25 13-28-54

**Comment by evrifaessa** [comment]
There should be better ways to achieve this. We could set up hooks and create applets that connect with them.

For example, the user could install GTM, Matomo, Intercom, whatever they want using the plugin/extension store, then the plugin would connect with the appropriate hooks.

This will be easy for the user, and we won't have to hardcode each app into each theme.

**Comment by evrifaessa** [comment]
I'll share more ideas about this in the evening. (UTC+3, evening is ~6 hours away now)

**Comment by jaapmarcus** [comment]
Ideally we should create a module for each of those.  Instead hardcoding it

**Comment by andpavlenko** [comment]
If you don't use GTM in practice, probably don't understand it concept of use?

**Comment by andpavlenko** [comment]
> Ideally we should create a module for each of those. Instead hardcoding it

I doubt that in new system on Laravel will be save old modules system.

**Comment by gOOvER** [comment]
> If you don't use GTM in practice, probably don't understand it concept of use?

Could be problems in Europe because of the DSVGO. Please integrate the whole thing as a module and not hardcoded, as already mentioned

**Comment by andpavlenko** [comment]
> Could be problems in Europe because of the GDPR.

This already refactored to custom code in theme settings. See [546fcde](https://github.com/FOSSBilling/FOSSBilling/pull/85/commits/546fcdef6c0bc8f4e8f570fc89c4e32056951a7c)

P.S. How do you conmect analytics in Europe for GDPR satisfaction?

**Comment by jaapmarcus** [comment]
You can’t really

**Comment by andpavlenko** [comment]
@gOOvER @jaapmarcus 
No external code now. See last commit!

**Comment by andpavlenko** [comment]
Screenshot from 2022-05-30 10-48-25

**Comment by andpavlenko** [comment]
Screenshot from 2022-05-30 10-48-25

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
