### PR TITLE
Enhance Huraga with Bootstrap 5 Support and Design Improvements

### PR DESCRIPTION
**Pull request by shmshd**
- Setup Webpack Encore build
- Minor redesign with Bootstrap 5
- Replace outdated flags library for locale selector
- Replace awe icons with MDI svg icons
- Replace Order page `iframe` with twig include

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Hi, @shmshd I was wondering what the status of this PR is?
What's left before it can be ready for review?

Is there anything I can help with?
Thanks!

**Comment by shmshd** [comment]
@BelleNottelling I should be able to continue the work after this week. In the meantime, could you please test the PR and find out any missing or broken designs? Thanks

**Comment by BelleNottelling** [comment]
@shmshd Sure, I'll try to do that in the next few days and I'll let you know what I find.
I can already tell you that it's going to be conflicted and missing a few templates that are in the main branch due to how long ago both Huraga PRs started

**Comment by BelleNottelling** [comment]
@shmshd Sorry for the delay, I got caught up & distracted with other stuff.
I've reviewed the changes in the PR and minus a couple of exceptionally minor things I think it looks great.

Unless there's any objections from you, I would like to merge this into the upstream branch at which point I'll take care of handling the conflicts and back-porting any work that has been done since (it's not much) & then make it ready for reviews.

Thanks for the hard work!

**Comment by BelleNottelling** [comment]
Moving forward as stated.
Thanks again for the great contributions, @shmshd!

I'll get the conflicts resolved, finish off and rough edges, and then move forward from there :)

**Pull request merged**
