### PR TITLE
Huraga dependency cleanup

### PR DESCRIPTION
**Pull request by evrifaessa**
Working on #314. Mostly cleaning up dependencies, moving them to their own file to make the source files more organized and to avoid shipping the same dependency with 4 different files.

### CODE REVIEW

**Comment by John-S4** [comment]
You might want to update to a newer version of FA while you are in there - 3.0.2 is pretty ancient.

**Comment by evrifaessa** [comment]
> You might want to update to a newer version of FA while you are in there - 3.0.2 is pretty ancient.

Seems like they had a custom prefix for Font Awesome in Huraga. Might take more effort than a drop-in replacement.

**Comment by evrifaessa** [comment]
Seems like Font Awesome's migration guide goes as old as version 4. There isn't a guide about v3.

**Comment by John-S4** [comment]
> Seems like Font Awesome's migration guide goes as old as version 4. There isn't a guide about v3.

Well it is about a decade old, so maybe not overly surprising. There can't be many projects out there still using v3

**Comment by evrifaessa** [comment]
Also seems like Huraga uses different icon providers including something like Elusive Icons.
Another thing is the whole classes starting with "awe-" in Huraga's stylesheets. Might need to adjust them to get them working with v6.

**Comment by John-S4** [comment]
What is that link in the robots.txt file - www.sxw.org.uk/computing/robots/check.html ?

Takes me to the website of a stage lighting designer.

**Comment by evrifaessa** [comment]
> Takes me to the website of a stage lighting designer.

Ugh, that's how much staff has changed since the initial release of BoxBilling.

**Comment by evrifaessa** [comment]
@John-S4 you can take it over from now on.

**Comment by John-S4** [comment]
So, let's merge this now. Then later in the week I will separate out the structure and colour parts of the CSS, so we only have to maintain one sheet instead of four.

**Review by John-S4 — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
