### PR TITLE
Various Changes to Defaults

### PR DESCRIPTION
**Pull request by BelleNottelling**
1: Change the invoice prefix from "BOX" to "FOSS"
2: Fix a few URLs and one mention of BoxBilling with default blog entries
3: Opt to use /billing-admin instead of /bb-admin by default

### CODE REVIEW

**Comment by evrifaessa** [comment]
I think we should decide on what to replace /bb-admin with.

Can we go with something smaller?

**Comment by BelleNottelling** [comment]
> I think we should decide on what to replace /bb-admin with.
> 
> Can we go with something smaller?

I mean we can just do /admin..
I opted not to change it to /fb-admin due to "FB" usually being seen as "FaceBook"

**Comment by evrifaessa** [comment]
We could go with /admin. Much better than /bb-admin or /billing-admin.

**Comment by BelleNottelling** [comment]
> We could go with /admin. Much better than /bb-admin or /billing-admin.

Sounds good to me. I'll give people some time to give their opinion on it and then make the change if we all agree on it

**Comment by jaapmarcus** [comment]
/admin/ above /billing-admin/

**Comment by John-S4** [comment]
Agree, there is no real reason to append anything to /admin

**Comment by BelleNottelling** [comment]
Updated it to /admin as we discussed.
Should be ready for a review / merge

**Review by evrifaessa — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
