### PR TITLE
Add Beneficiary Name to Company Details

### PR DESCRIPTION
**Pull request by gilesytheking**
Relates to #1782 

Add Beneficiary Field to System Settings

Output Beneficiary Field on PDF Footer 

I couldn't find any other location where the bank details are shown. If other locations exist please let me know and I can update them as well.

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Not entirely sure what's going on with the tests here 👀 
Since I'm not seeing any super obvious syntax errors, I am assuming it's because you removed `company_name` from the `getFooterInfo` function.

However, even if it isn't because of that, I'd still like to see that get added back in as it's generally still useful and it should probably be there for custom PDF templates

**Comment by gilesytheking** [comment]
@BelleNottelling 

I have added back the company_name field into the getfooterinfo function - src/modules/Invoice/Service.php . 

The company_name is actually referenced else where in the PDF footer on line 97, so it needs to be in the array anyway.

Hopefully that will resolve the errors.

**Comment by BelleNottelling** [comment]
> Hopefully that will resolve the errors.

All but one, yes. You will need to update the expected array in the tests to include the newly added parameter.
https://github.com/FOSSBilling/FOSSBilling/blob/main/tests/modules/System/ServiceTest.php#L31

> I also noticed in the settings - Display bank account information on the bottom of every page? - but I cant see anywhere that other than the PDF that outputs the bank details. is this something you are working on?

This was added awhile ago in [this pull request](https://github.com/FOSSBilling/FOSSBilling/pull/1642/files#diff-8fe2d9acf8eaeec6536328b7d09eb4b12492a69d8ce8bc81711a495afbb2c4cf).
If you have a version of the Huraga theme that predates it, nothing will be shown.

Otherwise it should work although I personally haven't tested it

**Comment by gilesytheking** [comment]
@BelleNottelling - Going to review the original pull request and ensure all locations where the bank details should show are correct.

**Comment by gilesytheking** [comment]
@BelleNottelling 

Beneficiary name has been added to all locations that reference the bank details. (Invoice, Print & PDF)

I have also made some changes to the PDF template and CSS as described here - #1759

**Comment by John-S4** [comment]
> Test failed for spellcheck - I have added .Invoicefooter CSS class into /mod_invoice_print.html.twig line 71

I think the issue is that the `<div class='Well InvoiceFooter'>` should be `<div class="Well InvoiceFooter">`

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
I've rebased this pull request and resolved some formatting issues with it, however I have noticed something that makes me question if all of these changes have been tested yet.

In numerous locations you've used the `InvoiceFooter` CSS class that you have made, but the actual CSS for this is only defined in the PDF CSS, so the other locations won't have styling applied.

The `Well` class you've used in one location also appears to be undefined and both classes don't follow any normal naming conventions. Personally, I'd like to see the classes be lowercase and to have each word separated with dashes (`invoice-footer`)

**Comment by gilesytheking** [comment]
> I've rebased this pull request and resolved some formatting issues with it, however I have noticed something that makes me question if all of these changes have been tested yet.
> 
> In numerous locations you've used the `InvoiceFooter` CSS class that you have made, but the actual CSS for this is only defined in the PDF CSS, so the other locations won't have styling applied.
> 
> The `Well` class you've used in one location also appears to be undefined and both classes don't follow any normal naming conventions. Personally, I'd like to see the classes be lowercase and to have each word separated with dashes (`invoice-footer`)

This is all tested on my FOSS staging site. Please see screenshots below.

The 'InvoiceFooter' was already defined in the PDF template, I have not created it. IMO the bank details are output just fine without any styling, however I added the 'InvoiceFooter' class to other areas so that it can styled easier in future template updates.

The 'Well' class again is an existing class, I haven't created this. I added it to the bottom of the mod_invoice_print.html.twig to be in keeping with the rest of the page. The 'well' class is also used in the  mod_invoice_invoice.html.twig 

I fully understand where you are coming from in terms of the naming conventions, however I was just using the class how it was originally written. I can make further updates if required

image

image

image

image

**Comment by BelleNottelling** [comment]
I have road mapped this for 0.6.1 as we are at the very end of changes for 0.6.0 with #1602 being the final non-bug fix change planned for the release. Due to the changes that will be introduced with Huraga, the changes here will need to be redone, but I can assist with that if needed

**Pull request closed without merging**
