### PR TITLE
Add Open Collective Badge

### PR DESCRIPTION
**Pull request by HunterNyan**

### CODE REVIEW

**Review by notbasetwo — APPROVED** [review]
LGTM

**Review by evrifaessa — APPROVED** [review]
LGTM. And yes, we should get rid of some of the other badges.

**Comment by jaapmarcus** [comment]
So currently we have:

PHP Composer
Download
Latest Stand With Ukraine 
Discord
fossbilling Issues 
fossbilling Demo 
fossbilling Size
 License 
 Contributor Covenant
  CodeFactor
  
  We should probably remove:
  Demo?
  Repo size?
  Issues?
  Code factor?

**Comment by evrifaessa** [comment]
Not sure about CodeFactor but agree with the rest.

**Comment by HunterNyan** [comment]
We shoudl ditch these two, the others are fine
fossbilling Demo
fossbilling Size

**Comment by BelleNottelling** [comment]
> We shoudl ditch these two, the others are fine
> fossbilling Demo
> fossbilling Size
> 

That and I'm also for dropping the issues counter consider GitHub shows that on the repo automatically

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
