### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by BelleNottelling**
It still said 0.2.x was receiving security fixes, which it isn't.
Bumped it to 0.4.x and also fixed some minor formatting issues

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Why not using 0.x.x as supported?

**Comment by evrifaessa** [comment]
> Why not using 0.x.x as supported?

Because we don’t maintain 0.3, 0.2 and 0.1 anymore and don’t provide any security updates for them.

**Comment by jaapmarcus** [comment]
> > Why not using 0.x.x as supported?
> 
> Because we don’t maintain 0.3, 0.2 and 0.1 anymore and don’t provide any security updates for them.

Then we should just state latest...

Otherwise we keep updating them...

**Comment by admdly** [comment]
It might be a good idea to leave the old versions with a cross in the the supported column, to make clear they aren't supported, as @jaapmarcus suggested.

**Comment by BelleNottelling** [comment]
> It might be a good idea to leave the old versions with a cross in the the supported column, to make clear they aren't supported, as @jaapmarcus suggested.

That's like, the opposite of what he said, but I'm happy to do so either way

**Review by admdly — APPROVED** [review]
Thanks for the changes. ❤️

**Pull request merged**
