### PR TITLE
Fix spelling & grammar

### PR DESCRIPTION
**Pull request by DuncanBennie**

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
Still has typos
image

**Comment by DuncanBennie** [comment]
Thanks Belle, I also just wanted to say thank you for all of the amazing work you are doing/have done. I will be contributing financially to the project when I am in a position to do so.

**Review by admdly — APPROVED** [review]
LGTM - thanks for contributing. 🙂

**Review by BelleNottelling — APPROVED** [review]
Thanks for getting that cleared up

**Comment by BelleNottelling** [comment]
> I also just wanted to say thank you for all of the amazing work you are doing/have done. I will be contributing financially to the project when I am in a position to do so.

Thank you!
Even if you aren't in a position to contribute financially, PRs are always appreciated, even if they are something as simple as proved wording / fixed typos.

**Pull request merged**
