### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by AbhineshJha**
Fixed minor words and grammatical mistakes !!

### CODE REVIEW

**Review by John-S4 — COMMENTED** [review]
Personally I really don't see the need for either of these changes. 

'participate' and 'take part' are identical in meaning in this context, the only change there is the formality of the voice used, and personally I prefer the more casual 'take part' here. 

I'm also not explicitly against changing the word if others prefer participate.

**Comment by AbhineshJha** [comment]
hey @John-S4 ! i  respect your words , can i revert these changes..
but that grammatical mistake , what's perception on that ?

**Comment by BelleNottelling** [comment]
I personally prefer "participate" over "take part", but ultimately they both mean the same and it doesn't really matter all that much

**Comment by AbhineshJha** [comment]
But this pr has also one grammatical mistake..
Can u continue with that mistake.?

**Comment by evrifaessa** [comment]
Sorry but that's grammatically correct.

**Comment by AbhineshJha** [comment]
ok ! as your wish .

**Review by MrCerise — APPROVED** [review]

**Pull request closed without merging**
