### PR TITLE
[DON'T MERGE] Started removing / cleaning up deprecated functions

### PR DESCRIPTION
**Pull request by BelleNottelling**
I think most likely these have been here for at least the better part of a decade, so let's start to clear them up & remove them

### CODE REVIEW

**Comment by BelleNottelling** [comment]
Huraga had some old references to deprecated API calls, I updated any I found and believe everything is good to go now.

Whatever release includes this PR will need to have a version bump (0.3.0) as this is a breaking change and will likely break a lot of custom themes that were built off Huraga

**Review by John-S4 — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Review by evrifaessa — APPROVED** [review]

**Comment by BelleNottelling** [comment]
@evrifaessa Why did you add "[DON'T MERGE]" to the PR title?

**Comment by evrifaessa** [comment]
> @evrifaessa Why did you add "[DON'T MERGE]" to the PR title?

@BelleNottelling

> Whatever release includes this PR will need to have a version bump (0.3.0) as this is a breaking change

Holding it off until 0.3.0.

**Comment by jaapmarcus** [comment]
Don't hold of merging it will become a merge confict hell

**Comment by evrifaessa** [comment]
well, if we decided now is the time to release 0.3.0, go ahead.

**Comment by BelleNottelling** [comment]
Merged since we all seemed okay with the next version being 0.3.0

**Pull request merged**
