### PR TITLE
Copyright and license notice updates

### LINKED ISSUE #86: Clarification of copyright notice requirements
As discussed on Discord. 

There seems to be a bit of confusion about what we need to use as copyright information under the Apache 2.0 license, and given the fact that this is a fork of an existing project under that license. 

I have reached out to someone experienced in the field for clarification and am waiting for reply, after which we should update the copyright notice which currently only contains BoxBilling.

### PR DESCRIPTION
**Pull request by John-S4**
Copyright and license notices changed to correctly comply with the Apache 2.0 license.

Closes #86

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]
LGTM. Checks must pass though.

**Comment by John-S4** [comment]
Yeah... failing with 92 errors 🤔 

I didn't change any code anywhere really, mostly just copyright notices inside comments - I need to go out now but will look at it later.

**Comment by evrifaessa** [comment]
Seems like you've emptied some files entirely. That's why tests are failing. An example is `src/bb-modules/Invoice/Controller/Admin.php`

**Comment by John-S4** [comment]
Strange, will fix / redo it when I have a bit of time this afternoon.

**Comment by John-S4** [comment]
That was really strange. Anyway, fixed and all checks now passing.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
