### PR TITLE
Drop the Queue module

### PR DESCRIPTION
**Pull request by BelleNottelling**
This pull request drops the queue module. To the best of my knowledge, the only case where it was being used was via the massmailer module and it was used to queue emails. Problem with that is our email module *already* does email queuing so we had two separate modules being used to queue emails, each with different behavior.

## Pros
- Less code to maintain.
- Massmailer will now actually have limited number of tries for emails, like the default email system. Otherwise it would end up trying indefinitely
- No possibility of someone being confused when the massmailer email queue doesn't have / follow the same settings as the normal email settings

I've also added the ability to see the email queue from the email settings:
image

## Cons
- Having a generic queue module is actually useful and technically that's what the existing queue module does, however it's imo quite poor at that as it seems somewhat incomplete, is disabled by default, and is entirely separate from the core software. I also believe there are existing packages we can use which would allow us to build a better version than what currently exists.

### CODE REVIEW

**Review by admdly — APPROVED** [review]
Changes look good and no issues from brief testing. 🙂

**Comment by admdly** [comment]
It's not important for this PR, but I can't help feeling the functionality provided by the Massmailer module should really just be an option in the Client module. Perhaps a further merging of functionality could be done down the line?

**Comment by BelleNottelling** [comment]
> Massmailer module should really just be an option in the Client module

Eh.. I'd probably disagree. It's both a way to communicate info on mass and also a tool that can be used for sending marketing / promotional emails. In my opinion, it makes sense to have it separate & on it's own.

**Comment by BelleNottelling** [comment]
> You likely know the functionality better than me - I based my opinion on it only being used to communicate with clients. That said, I don't feel too strongly either way.

Honestly I didn't have a use for it until today, which is why I ended up sitting down to clean things up. First time I have used it outside of just verifying the test email will send, lol.

I also don't feel strongly about where it is, but personally I do think that it's best in it's own module.

**Comment by John-S4** [comment]
This makes sense to me and the changes look good. 

Regarding...

> In my opinion, it makes sense to have it separate & on it's own.

I share this opinion.

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
