### PR TITLE
Replace jQuery Alert with Tabler modal for Form Builder

### PR DESCRIPTION
**Pull request by shmshd**
Type | Image
-|-
New Form | image
Copy Form | image
Text | image
Dropdown | image
Radio | image
Checkbox | image
Textarea | image
Order Manage | image

### CODE REVIEW

**Comment by evrifaessa** [comment]
I'll give this PR an extensive review likely tomorrow.

**Review by evrifaessa — APPROVED** [review]
It looks beautifully done. Thanks for the great patch 🙂

**Comment by evrifaessa** [comment]
I think this should be the last place jPrompt is used. It should be fine to remove jAlert entirely after it's also migrated to the new Modals toolkit.

https://github.com/FOSSBilling/FOSSBilling/blob/fa9567bf491becb5ea71cb97eaf373e5fab0d0c3/src/themes/admin_default/assets/js/fossbilling.js#L188-L200

**Comment by admdly** [comment]
@evrifaessa looks like @shmshd has addressed the last jPrompt usage you mentioned. 😀 

I'm guessing you're happy for this to be merged, and jAlert removed (perhaps in a separate PR)? If so, I'll review and merge ASAP.

**Comment by evrifaessa** [comment]
I have a concern but I’m walking rn. Will comment in a few hours.

**Comment by evrifaessa** [comment]
Alright. My pretty small concern was removing the use of the "data-api-prompt-default" attribute. Other than that, the PR seems good to be merged.

**Comment by admdly** [comment]
> Alright. My pretty small concern was removing the use of the "data-api-prompt-default" attribute. Other than that, the PR seems good to be merged.

Good point - though looking through the code, it looks like `data-api-prompt-default` is never actually used. It should be easy enough to add back, but is it worth it in this case?

**Comment by evrifaessa** [comment]
> but is it worth it in this case?
I think it is. Especially for prompts where you edit existing data.

**Comment by admdly** [comment]
OK - @shmshd could you restore `data-api-prompt-default` as discussed above? Once this has been addressed and @evrifaessa is happy, I will go ahead and review/merge. :smile:

**Comment by shmshd** [comment]
@admdly it is fixed. It was mistakenly missed when I did the change quickly

**Comment by evrifaessa** [comment]
> I think it is better to remove `jquery.alert` library and the dependent npm package in this PR.

Yeah, makes sense.

**Review by evrifaessa — APPROVED** [review]

**Pull request merged**
