### PR TITLE
Remove docker dependency from make test target

### PR DESCRIPTION
**Pull request by DataLores**
Remove docker dependency from make test target

### CODE REVIEW

**Comment by evrifaessa** [comment]
Anything wrong with using Docker for it? @DataLores

**Comment by DataLores** [comment]
I have not yet been able to figure out the secret sauce to resolving the current docker image's inability to find the 'composer' executable on the "make test" target

"docker-compose exec php composer install --working-dir=src --no-progress --no-suggest --prefer-dist

OCI runtime exec failed: exec failed: unable to start container process: exec: "composer": executable file not found in $PATH: unknown"

**Comment by evrifaessa** [comment]
@DataLores the PHP image won't include Composer by default. You can use the Composer commands using the official Composre image (https://hub.docker.com/_/composer) or copy the Composer executable from the Composer image to the PHP container (https://stackoverflow.com/a/58694421).

I don't have that much experience in Docker but I think the way to go here would be using the Composer image for Composer commands.

**Comment by evrifaessa** [comment]
@DataLores, #294 should fix this.

**Comment by evrifaessa** [comment]
Fixed with #294.

**Pull request closed without merging**
