### PR TITLE
Tried to create China Unionpay Adapter

### PR DESCRIPTION
**Pull request by 123ysys**
I am new to PHP, this change may contain serious bugs or not work properly, need strict code review, preferably with feedback on code availability reasons.

### CODE REVIEW

**Comment by jaapmarcus** [comment]
We have decided to maintain only a few payment modules / custom modules and move everything else to seperate repo's so it is easier to maintain for both us and you as the developer.

Also with out login details or an account with Unionpay it is for impossible to test. 

Also why is [rc/library/Payment/AdapterAbstract2.php](https://github.com/FOSSBilling/FOSSBilling/pull/837#diff-f6d3a0c10fa601e9963fe3253dac6de4dac14fea56934f02cc52cfacb6e5d975)

Created any custom values should be listed in the UnionPay plugin and not in a separate file.

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
Was this even tested? There are tons of syntax errors and very obvious mistakes in how it was built

**Comment by John-S4** [comment]
I've changed this to draft because as @BelleNottelling pointed out above it is definitely not close to ready for use. 

As @jaapmarcus said, we are not going to include or maintain every payment module or extension as a part of core FOSSBilling, but we definitely do welcome the contributions. It may be better if this is maintained in a separate repository by the author, and we can then add it to the working extensions list and add it to the extension store when that is ready in the future.

**Comment by BelleNottelling** [comment]
Hello, @123ysys 
Do you intend on completing this PR? In it's current state, we can't merge this

**Comment by 123ysys** [comment]
I am sorry for the confusion,

**Pull request closed without merging**
