### PR TITLE
Laravel Update

### PR DESCRIPTION
**Pull request by kennysinkeler**
Added Legacy Tables 
Added the Models (without relationships) 
Added Admin Login(with the AdminTable)
Drop 2 columns on the Admin table (role and permissions) for supporting Spatie/Permissions.
Removed Solumsvm/forum en public ticket tables

### CODE REVIEW

**Comment by John-S4** [comment]
I don't have a lot of experience with Laravel, otherwise I'd be jumping in and helping out more with this, but everything in here looks like it makes sense to me.

**Review by jaapmarcus — COMMENTED** [review]
Changes look fine. 

We should decide if we want to drop certain features like Forum instead invest time in migrating it and then drop it any way.

**Comment by kennysinkeler** [comment]
> We should decide if we want to drop certain features like Forum instead invest time in migrating it and then drop it any way.

Maybe start with the core feature's and release the features like Forum as a module?

**Comment by jaapmarcus** [comment]
> > We should decide if we want to drop certain features like Forum instead invest time in migrating it and then drop it any way.
> 
> Maybe start with the core feature's and release the features like Forum as a module?

That was the plan more or less...

**Comment by John-S4** [comment]
Exactly as was previously discussed. 

My personal opinion is that a forum should never be a core part, or probably even a core team supported module. In the case that someone does need one then the best option would probably be a module that bridges to an existing forum solution, i.e. Flarum

I know that's a bit off topic, but it illustrates the philosophy of making an extensible core that doesn't have any unnecessary (and a pain in the ass to support) fluff in it, which is what we are aiming for.

**Comment by evrifaessa** [comment]
Yeah, forum should be dropped entirely.

**Pull request merged**
