### PR TITLE
Drop Markitup Editor support

### PR DESCRIPTION
**Pull request by jaapmarcus**

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
This won't work for existing installs. You need to make it fallback to the default (CKEditor) if markitup is still set enabled.

Easiest way is to just remove the if, since CKEditor is the only option available

**Comment by BelleNottelling** [comment]
it would also probably be best practice to re-create the `assets` folder and create a `.gitkeep` file, as this folder is still used

**Review by BelleNottelling — APPROVED** [review]

**Review by John-S4 — APPROVED** [review]
Are we absolutely sure that CKEditor is implemented everywhere?

If yes, then this seems all good to me.

**Comment by BelleNottelling** [comment]
> Are we absolutely sure that CKEditor is implemented everywhere?
> 
> If yes, then this seems all good to me.

Yes, everything should be including the `src/modules/Wysiwyg/html_admin/mod_wysiwyg_js.html.twig` file, which was used to switch between the different WYSIWYG editors

**Pull request merged**
