### PR TITLE
Add release drafter

### PR DESCRIPTION
**Pull request by evrifaessa**
Release drafter will create a drafted changelog and update it with each PR.
It can distinguish the mission of the pull request by it's labels and place them accordingly.

Given a version number **vMAJOR.MINOR.PATCH**, release drafter will automatically

* Bump the MAJOR version when we make incompatible API changes and label the PR 'major',
* Bump the MINOR version when we add functionality in a backwards compatible manner and label the PR 'minor', and
* Bump the PATCH version when we make backwards compatible bug fixes.

It will check the latest release and bump it's PATCH version by default, if none of the PRs are labeled 'minor' or 'major'.

It will also ignore PRs labeled 'skip-changelog'.

-----

It will look like this:

Release drafter

-----

Check the action on GitHub Marketplace:
https://github.com/marketplace/actions/release-drafter

### CODE REVIEW

**Comment by evrifaessa** [comment]
The workflow fails because it tries to grab the configuration file from the main branch, it will exist in the main branch once the PR is merged.

**Review by andpavlenko — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Review by BelleNottelling — APPROVED** [review]

**Comment by gOOvER** [comment]
this is missing:

https://github.com/release-drafter/release-drafter#configuration

**Comment by evrifaessa** [comment]
> this is missing:
> 
> https://github.com/release-drafter/release-drafter#configuration

It's not. It's under /.github

**Comment by John-S4** [comment]
Never used this and tbh haven't clicked and read, but I'm assuming you can still manually change the draft it produces? Because not every commit needs to be included a changelog.

**Pull request merged**
