### PR TITLE
Fix validateAndSanitizeEmail for international domains

### PR DESCRIPTION
**Pull request by BelleNottelling**
Did some more research and testing, the filter_var sanitization would remove accented letters, thus breaking international domains. `htmlspecialchars` won't do that, and it will still provide some sanitization.
Also created testcases

### CODE REVIEW

**Comment by BelleNottelling** [comment]
I'm not sure if phpunit is actually executing the tests I created. I don't have much experience with it

**Comment by BelleNottelling** [comment]
I figured out why the tests weren't running, but I'm confused as to why they are failing in the way they are,
@evrifaessa @jaapmarcus do either of you have any ideas?

**Comment by BelleNottelling** [comment]
@jaapmarcus @evrifaessa I've disabled the test since it's not working correctly. It's not really needed either way.
I have tested and verified that this change does work as intended, however. International domains are validated correctly, and the sanitized return matches the original & should still work correctly.

Let's get this merged so those emails will be properly validated

**Review by evrifaessa — APPROVED** [review]
LGTM

**Comment by jaapmarcus** [comment]
We should wait for https://github.com/symfony/polyfill-intl-idn that @BelleNottelling  is planning to use.

**Comment by BelleNottelling** [comment]
Added it. Per the readme, it looks like all we need to do is include it:
https://github.com/symfony/polyfill/blob/main/README.md

**Comment by evrifaessa** [comment]
Just tested, it now seems to be working without the intl extension installed and enabled.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
