### PR TITLE
fix(internet.bs registrar): review function getTlds to be api-driven

### PR DESCRIPTION
**Pull request by KaiSchwarz-cnic**
Just implemented, not tested as we have no FOSSBilling System up and running.

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
Sorry, but this doesn't actually look like a valid implementation unless the test links they show  in the docs are incorrect.

Take a look at the output for this:
https://testapi.internet.bs/Account/PriceList/Get?ApiKey=testapi&Password=testpass

The pattern of `product_$i_tld` doesn't match

**Comment by KaiSchwarz-cnic** [comment]
@BelleNottelling In that point you're incorrect. The test link used works, yes, but it is not reflecting the getTlds Implementation.
`$params` used within the IBS adapter multiple times represents additional GET parameters to use. This again means that those are missing in the test link used.

The right test link would be:
https://testapi.internet.bs/Account/PriceList/Get?version=5&ApiKey=testapi&Password=testpass

There, you'll find the data used in the `foreach` loop.

Hope that helps!

**Comment by jaapmarcus** [comment]
https://github.com/search?q=repo%3AFOSSBilling%2FFOSSBilling%20getTlds&type=code

**Comment by BelleNottelling** [comment]
> The right test link would be: https://testapi.internet.bs/Account/PriceList/Get?version=5&ApiKey=testapi&Password=testpass
> 
> There, you'll find the data used in the `foreach` loop.

Oh thank you, you are correct in that case. My bad! 

However, @jaapmarcus is correct. On a closer inspection, the `getTlds` function is never actually referenced anywhere. In fact, I even went and tried checking BoxBilling versions from about 10 years ago and still couldn't find any instance of it being used.

Probably best just to remove the function entirely from our source code to remove confusion. At the end of the day it seems unneeded to begin with as I'd expect a registrar to simply report a domain as unavailable if we try to check a TLD that it doesn't support.

Sorry! Thanks for the efforts, though :)

**Pull request closed without merging**
