### PR TITLE
Add verification before permitting password change

### LINKED ISSUE #541: Verify current password before changing the password
Both the admin panel and the client area provide an option to change the current user's password. It should also verify the current password before allowing the change.

### PR DESCRIPTION
**Pull request by admdly**
Verify current password before allowing staff or clients to change password (closes #541).

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Comment by admdly** [comment]
Closes #541.

**Comment by evrifaessa** [comment]
Haven’t really tested it yet, just wanted to note that we should properly document this change because it will break the feature in every theme in existence.

**Comment by admdly** [comment]
Agree re: documentation as it will break themes. Perhaps it would be better to simply rewrite authentication as a separate module to build on going forward , if it's going to be a breaking change anyway?

**Comment by evrifaessa** [comment]
@admdly what are the details and benefits? I’m all in for meaningful breaking changes before 1.x.

**Comment by admdly** [comment]
@evrifaessa we've discussed this a bit on Discord, and I note the medium term plan (prior to v1) is to implement an Auth module. However, please find the documentation for this below to permit this to be merged now:

### API Endpoints Changed
- /api/admin/profile/change_password
   - Required fields:
       - current_password - Current admin user password.
       - new_password - New admin user password.
       - confirm_password - New admin user password confirmation.
- /api/client/profile/change_password
   - Required fields:
       - current_password - Current client user password.
       - new_password - New client user password.
       - confirm_password - New client user password confirmation.

### Affected Theme Files 
- mod_client_profile.html.twig
- mod_staff_profile.html.twig

**Review by John-S4 — APPROVED** [review]

**Comment by John-S4** [comment]
Great commit - thanks @admdly

**Review by BelleNottelling — APPROVED** [review]

**Pull request merged**
