### PR TITLE
chore: Refactor OrderButton module to use more theme assets instead of overriding

### PR DESCRIPTION
**Pull request by mvarrieur**
Re: https://github.com/FOSSBilling/FOSSBilling/issues/249

OrderButton was providing it's own CSS files which means it also needed to get rid of googlefonts. I refactored the OrderButton module to use the theme assets instead of providing it's own.

_Note:_  This is my first time working in this repo so this could definitely use a second or third set of eyes to make sure I didn't mess anything up.

### CODE REVIEW

**Comment by evrifaessa** [comment]
I think it’d be better if we get them to share assets instead of shipping the CSS and font files twice. I also don’t know why the Orderbutton module depends on Huraga’s full CSS in the first place.

**Comment by mvarrieur** [comment]
@evrifaessa yeah that's fair, I was trying to follow the pattern of what was there, but I can try to move things around later tonight and get them to share these files. I noticed that FontAwesome + Elusive were also replicated in both places so I thought there might be a reason for it

**Comment by John-S4** [comment]
> I noticed that FontAwesome + Elusive were also replicated in both places so I thought there might be a reason for it

To be honest, you are likely to find a lot of things throughout the code that there seems to be no logical reason for. The best thing we can do is to clean them up as we go along.

**Comment by mvarrieur** [comment]
I took a stab at making OrderButton use more of the theme assets instead of providing it's own, but this is my first time working in this repo so this could definitely use a second or third set of eyes.

**Review by evrifaessa — APPROVED** [review]

**Comment by evrifaessa** [comment]
Looks good to me. Tested and saw that the module now depends on Huraga's assets and works fine.

image

Thanks for the PR. We'd be really glad to see more of them. You can also join our [Discord server](https://fossbilling.org/discord) to keep in touch with the community :)

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
