### PR TITLE
Massmailer bugfixes & improvements

### PR DESCRIPTION
**Pull request by BelleNottelling**
This PR fixes and improves the massmailer module further.

## New feature

I've modified the API and front-end so that you can now see the list of recipients for a message. This will automatically be populated after clicking the preview button.

image

## Fixes

- Fixed the filters in the UI. Previously, they did not save
- Prevented the possibility of a single client being duplicated in the recipient list, (11 times in this example)
- Minor optimizations

### Before

With the extra info being fetched from the DB & nothing to prevent a client from being added multiple times

```PHP
Array
(
   [0] => Array
       (
           [id] => 4
           [first_name] => Johnie
           [last_name] => Doe
       )
   [1] => Array
       (
           [id] => 3
           [first_name] => Jannet
           [last_name] => Doe
       )
   [2] => Array
       (
           [id] => 2
           [first_name] => John
           [last_name] => Doe
       )
   [3] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [4] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [5] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [6] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [7] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [8] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [9] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [10] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [11] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [12] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [13] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
   [14] => Array
       (
           [id] => 1
           [first_name] => Jane
           [last_name] => Doe
       )
)
```

### After

Without the extra info being fetched from the DB & prevention from a client from being added multiple times

```PHP
Array
(
    [0] => Array
        (
            [id] => 4
        )
    [1] => Array
        (
            [id] => 3
        )
    [2] => Array
        (
            [id] => 2
        )
    [3] => Array
        (
            [id] => 1
        )
)
```

### CODE REVIEW

**Review by evrifaessa — APPROVED** [review]

**Comment by BelleNottelling** [comment]
Looks like `DISTINCT` may have a measurable hit to performance. https://stackoverflow.com/questions/5341276/sql-distinct-keyword-bogs-down-performance/5344601#5344601

I'll mark this as a draft and run through a script to create like 10k test clients and see what kind of impact it has

**Comment by BelleNottelling** [comment]
## Results
Time to query the client list was almost identical for both options, however using `DISTINCT` did end up being a bit faster.
This is pulling 26.5k clients from the DB. I've left it using `DISTINCT` based on these results.

Using PHP:
Execution time: 0.044584609 seconds

Using DISTINCT:
Execution time: 0.038741386 seconds

## Other changes
My most recent commit also fixes the filters in the UI (they previously wouldn't save) and did a micro-optimization in the send workflow to prevent the system from needing to pull the message from the DB for each recipient.

**Review by admdly — APPROVED** [review]
Nice work 🙂. 

One observation - is there any reason the array is still a multidimensional array and not a simple list of IDs now the extra data has been dropped?

**Review by jaapmarcus — APPROVED** [review]

**Comment by BelleNottelling** [comment]
> Nice work 🙂. 
> 
> One observation - is there any reason the array is still a multidimensional array and not a simple list of IDs now the extra data has been dropped?

That's just how it's returned when querying the DB. I'm unsure if we can actually change that behavior

**Pull request merged**
