### PR TITLE
#1717  Add "Port" option on add hosting server page

### LINKED ISSUE #1717: [Feature Request] Directadmin Servers on non-standard port
**Is your feature request related to a problem? Please describe.**
I can't connect to Directadmin installation because I use DA on non standard port 8443 instead 2222

**Describe the solution you'd like**
Add a new text input for port to connect

### PR DESCRIPTION
**Pull request by jaapmarcus**
Closes #1717

### CODE REVIEW

**Review by BelleNottelling — CHANGES_REQUESTED** [review]
This is does nothing to close the linked issue, the DirectAdmin server manager does not even look at the `port` configuration option.

https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/Server/Manager/Directadmin.php

**Comment by jaapmarcus** [comment]
I assumed it did at least it will solve the issues for other server adapters...

**Comment by jaapmarcus** [comment]
Don't have an Directadmin server to test it on how ever I can confirm setting custom port works...

**Review by BelleNottelling — APPROVED** [review]
LGTM

**Pull request merged**
