### PR TITLE
Continue work on the admin theme

### PR DESCRIPTION
**Pull request by andpavlenko**
- Build SVG sprite
- Remove unused images
- Fix typos

### CODE REVIEW

**Comment by BelleNottelling** [comment]
btw, I noticed this today while experimenting with the demo module:
image

Looks like there may be an issue with popups / alerts not being fully updated.

**Comment by andpavlenko** [comment]
> Looks like there may be an issue with popups / alerts not being fully updated.

I don't touch jAlert styles, because will need to remove it when work on JS...

**Comment by evrifaessa** [comment]
The homepage has some hard-coded statistics like "12 suspended" and "32 suspended".

**Comment by evrifaessa** [comment]
mod_currency

Templates coming from the modules are broken. We should fix them after deciding on what to drop and what to keep, and before making our initial release.

**Comment by evrifaessa** [comment]
Unreadable text

Text inside the table seems to be unreadable in dark mode.

**Comment by evrifaessa** [comment]
User

Can we show more information like user e-mail, country, avatar and name instead of just the name?

**Comment by andpavlenko** [comment]
@evrifaessa Lets make describe particular problems in separate issues. Anyone could find info in issue tracker and solve problem with separate PR.

**Review by evrifaessa — APPROVED** [review]

**Review by John-S4 — APPROVED** [review]
I saw 747 files changed and panicked a bit, but happily mostly images :)

Can't see any big or quickly noticeable issues, all seems to be working as it should, and changes make sense.

**Comment by Komodroid** [comment]
Some unused images weren't actually unused images:
msedge_Vr7FBk2IUf

From deleted directory:
explorer_Z3pJmZFWQ5

@andpavlenko

**Comment by Komodroid** [comment]
Do we bring back that folder or migrate to the new icons directory/svg files?

**Comment by John-S4** [comment]
> Do we bring back that folder or migrate to the new icons directory/svg files?

The second option is better I think. 

Maybe @andpavlenko can take a look and add those icons back in?

**Comment by andpavlenko** [comment]
@Komodroid @John-S4 
Already fixed in PR #85 commit [f5d1cdb](https://github.com/FOSSBilling/FOSSBilling/pull/85/commits/f5d1cdbe096af407abbcbcff42d6db7f1f28a9d5)

**Pull request merged**
