### PR TITLE
Use dompdf for PDF generation

### PR DESCRIPTION
**Pull request by BelleNottelling**
Replace outdated TFPDF with [dompdf](https://github.com/dompdf/dompdf)
Benefits are:
1: Newer, still maintained.
2: Full support for modern PHP versions. IE: No more hacked together files
3: Through composer. Less files we need to manually update
4: Actually has slightly better image support than the current implementation, more specifically partial SVG support
5: HTML for invoices. Potentially using a template later down the line? 

This is currently how the PDFs look. I'm not very good with CSS so I'm open to suggestions or help with it
image

### CODE REVIEW

**Comment by John-S4** [comment]
I'm not in front of a computer much this weekend so I haven't really looked too deeply, but... for now it would probably be enough to set a max-width on whatever the div that is holding the company info is (and the client info one as well). 

Oh, and maybe reduce the thickness and darken that hr and then it should look pretty reasonable I'd think.

**Comment by BelleNottelling** [comment]
Played around with the CSS a bit more. It's definitely looking better, but it would still benifit from more work.
Not sure why the "total" isn't displaying for each line item like it used to, it's using the same code to pull it that the old PDF generator used. I'll have to figure that out
image

**Review by evrifaessa — APPROVED** [review]

**Comment by John-S4** [comment]
@BelleNottelling Looks pretty good to me. It might not be the most beautiful thing in the world, but it's clear and legible and works, and it's an invoice after all :)

I think we should merge it and then the appearance can be worked on later, we need to focus on getting things fixed and working.

**Review by John-S4 — APPROVED** [review]

**Comment by BelleNottelling** [comment]
@John-S4 functionally this PR should be complete. 
I may revamp some things or add new features later down the line, but that's not going to be part of this PR

**Pull request merged**
