### PR TITLE
Order button css

### PR DESCRIPTION
**Pull request by reynaldiarya**

### CODE REVIEW

**Review by jaapmarcus — COMMENTED** [review]
Please provide some screenshots with the changes you make

**Comment by reynaldiarya** [comment]
[https://ibb.co/y6920cc](url)
and
[https://ibb.co/Kj2Kbd1](url)

**Comment by reynaldiarya** [comment]
before
[https://ibb.co/bRb7zMY](url)
[https://ibb.co/mJYLgg1](url)

**Review by jaapmarcus — APPROVED** [review]

**Comment by jaapmarcus** [comment]
Edited the links so you can click on it

**Review by John-S4 — APPROVED** [review]

**Pull request merged**
