### PR TITLE
Fix `admin_default` layout on bigger screens

### PR DESCRIPTION
**Pull request by shmshd**
### Before
before

### After
after

### CODE REVIEW

**Comment by BelleNottelling** [comment]
I'm gonna be honest.. I don't think that's an improvement. That just feels like there's too unused and wasted space going on. Is there no way to go somewhere in the middle of the two?

**Comment by shmshd** [comment]
> I'm gonna be honest.. I don't think that's an improvement. That just feels like there's too unused and wasted space going on. Is there no way to go somewhere in the middle of the two?

Keeping the content in the centre is the standard for bigger screens. Moving it to the right or left will bring in more wasted space on any of the opposite sides. Flexing them to both sides is really bad as text fields and flexed out buttons will look like a long road.

**Comment by shmshd** [comment]
> I would personally prefer option 1 then 2...

what options?

**Comment by jaapmarcus** [comment]
Keep it as it... 

I don't usually use my 4k screen full screen  But even I will get crazy onto the white space....

**Comment by BelleNottelling** [comment]
> > I'm gonna be honest.. I don't think that's an improvement. That just feels like there's too unused and wasted space going on. Is there no way to go somewhere in the middle of the two?
> 
> Keeping the content in the centre is the standard for bigger screens. Moving it to the right or left will bring in more wasted space on any of the opposite sides. Flexing them to both sides is really bad as text fields and flexed out buttons will look like a long road.

I have a high resolution, large display. It's 2560x1440p and 32 inches. I don't disagree that there should be some white space, but in my opinion this creates too much

**Comment by shmshd** [comment]
> I have a high resolution, large display. It's 2560x1440p and 32 inches. I don't disagree that there should be some white space, but in my opinion this creates too much

I too use the same display, which is why I created this PR. If everyone disagrees with this PR, let it be closed. Someday we can bring config for `admin_default` to customize the layout similar to Huraga.

**Comment by jaapmarcus** [comment]
> 

I wonder how many users use it in full screen mode...  If they have such large screens. Probally not a lot (And if they do they should be murdered..)

**Comment by John-S4** [comment]
I'd agree that is a negative change rather than a positive one. 

It's far from ideal right now, but I don't think this is the right way to fix it.

**Comment by BelleNottelling** [comment]
Hey, @shmshd
I'm going to close this as superseded by https://github.com/FOSSBilling/FOSSBilling/pull/947

**Pull request closed without merging**
