### PR TITLE
Fix Reseller Club

### PR DESCRIPTION
**Pull request by jaapmarcus**
Fix issues by fixing the error reporting...

### CODE REVIEW

**Comment by jaapmarcus** [comment]
Fixes: https://github.com/FOSSBilling/FOSSBilling/issues/2096

**Comment by BelleNottelling** [comment]
Does this fix #1733 as well?
Also I thought you said that a bunch of the API endpoints were removed, doesn't look like any of those have been updated here...

**Comment by jaapmarcus** [comment]
> Does this fix #1733 as well? Also I thought you said that a bunch of the API endpoints were removed, doesn't look like any of those have been updated here...

No it seems still to be fine the  move to http-client broke more or less the handling..

$result -> toarray()  causes to trigger an exception ...

I have tested it against the end points and it works fine.

**Review by BelleNottelling — APPROVED** [review]
LGTM.
I still hate how their API doesn't always return JSON, but there's not much we can do about it

**Comment by jaapmarcus** [comment]
> LGTM. I still hate how their API doesn't always return JSON, but there's not much we can do about it

It took me way to long to find that out ...

Also their support issn't either the best ...

**Review by admdly — APPROVED** [review]

**Pull request merged**
