### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by evrifaessa**

### CODE REVIEW

**Comment by jaapmarcus** [comment]
We should probably move to a once in a week sync instead of every x hours

**Comment by evrifaessa** [comment]
> We should probably move to a once in a week sync instead of every x hours

The most you can do it 24 hours. I changed it to 24 hours.

**Comment by BelleNottelling** [comment]
I am fine with these change, but please make sure to do a squash and merge with this

**Comment by evrifaessa** [comment]
> I am fine with these change, but please make sure to do a squash and merge with this

of course. for some reason Crowdin separates each file into it's own commit. I'll try to have it commit only once a day.

**Pull request merged**
