### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by John-S4**

### CODE REVIEW

**Review by BelleNottelling — COMMENTED** [review]
I feel like we should retain the comment regarding security & stability

**Comment by John-S4** [comment]
> I feel like we should retain the comment regarding security & stability

I ummed and aahed about it for a few minutes and really couldn't decide. I think ultimately I didn't want to make the warning text overly long, but maybe you are right. Will reinstate it and just add the versioning bit on.

**Review by BelleNottelling — APPROVED** [review]
Works for me

**Comment by jaapmarcus** [comment]
> I feel like we should retain the comment regarding security & stability

Disagree we should fully disclose as much as possible regarding security maybe at a delay. If somebody goes to the public available commits the still will notice it. And it is in the open. There is nothing wrong to say we  accidentally messed something up and be careful with it.

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
