### PR TITLE
Automatically execute cron

### PR DESCRIPTION
**Pull request by BelleNottelling**
When it hasn't run in at least 15 minutes / hasn't run at all & display a warning to the user. 
As an alternative to https://github.com/FOSSBilling/FOSSBilling/pull/179.

This this has the added bonus that even without configuring cron it will still get periodically run & warn the user that it's not working correctly 
Example:
image
And proof that it did run when I opened this page:
image

### CODE REVIEW

**Comment by BelleNottelling** [comment]
These tests are going to be the bane of my existence

**Comment by evrifaessa** [comment]
There should be a toggle for this. Maybe a key in the configuration file?

**Comment by BelleNottelling** [comment]
Why do we need a toggle?

**Comment by evrifaessa** [comment]
I checked the PR as soon as I woke up. Seems like I didn’t read the part saying “When it hasn't run in at least 15 minutes / hasn't run at all”.

It should be fine.

**Review by evrifaessa — APPROVED** [review]

**Comment by John-S4** [comment]
Yep, no need for a toggle because of the time check.

**Review by John-S4 — APPROVED** [review]

**Comment by jaapmarcus** [comment]
I would prefer to send an email or find other ways to notify the command instead this could cause strange issues if for what kind of reason the cronjob didn't run for a longer period of time

**Comment by BelleNottelling** [comment]
> I would prefer to send an email or find other ways to notify the command instead this could cause strange issues if for what kind of reason the cronjob didn't run for a longer period of time

Why do you think it would cause issues if cron hasn't been run in a long time?

**Comment by evrifaessa** [comment]
Some might want to do it in intervals longer than 15 mins or at entirely custom times. It should be up to the system administrator to decide if it should be automatically ran or not.

As an example, bigger companies with bigger databases might want to do it once a day in the least busy time. Some might want to do it every 5 minutes.

It’s fine to do it for smaller and new users and make it on by default, but more advanced users should be able to disable it.

**Comment by BelleNottelling** [comment]
> Some might want to do it in intervals longer than 15 mins or at entirely custom times. It should be up to the system administrator to decide if it should be automatically ran or not.
> 
> As an example, bigger companies with bigger databases might want to do it once a day in the least busy time. Some might want to do it every 5 minutes.
> 
> It’s fine to do it for smaller and new users and make it on by default, but more advanced users should be able to disable it.

I really doubt this is a problem, but I created https://github.com/FOSSBilling/FOSSBilling/pull/402 to account for it

**Pull request merged**
