### PR TITLE
Fixed custom pages not working in nginx

### LINKED ISSUE #383: [Bug] Custom pages don't work
**Describe the bug**
Custom pages don't work and display 404 errors in Huraga. I don't know why it happens, but one possible cause might be the Huraga theme.

I don't know how it was integrated back then. But if it was integrated in a theme-level, we had 3 themes before and might have left out Huraga while doing the work.

**To Reproduce**
1. Enable the "Custom Pages" extension
2. Go to "admin/custompages" and create a new custom page
3. Click the first button in the action menu
4. It will take you to a non-existent page

**Expected behavior**
The custom page should appear regularly.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Mozilla Firefox

**Server**
- Web server: nginx

### PR DESCRIPTION
**Pull request by evrifaessa**
Fixes #383.

This specific configuration existed in the Apache configuration but not in the nginx configuraiton. It should now work.

Already pushed to the configuration generator, this PR fixes it for our Docker environment.

Also moved the nginx configuration to the [new configuration generator tool](https://config.fossbilling.org) while leaving a note announcing the move.

### CODE REVIEW

**Review by BelleNottelling — APPROVED** [review]

**Comment by evrifaessa** [comment]
@jaapmarcus you're experienced with nginx, can you double-check if I have done anything wrong or not? Thanks.

**Comment by BelleNottelling** [comment]
Let's make sure that gets added to the config generator, too

**Comment by evrifaessa** [comment]
> Let's make sure that gets added to the config generator, too

I was working on it right now.

**Review by jaapmarcus — CHANGES_REQUESTED** [review]
Keep at least a working example available in the repo. Add a note with the configurator tools should be enough

**Comment by evrifaessa** [comment]
@BelleNottelling @jaapmarcus can you check now?

**Review by BelleNottelling — APPROVED** [review]

**Review by John-S4 — APPROVED** [review]

**Review by jaapmarcus — APPROVED** [review]

**Pull request merged**
