### PR TITLE
fix(internet.bs registrar): review function isDomaincanBeTransferred

### PR DESCRIPTION
**Pull request by KaiSchwarz-cnic**
an internet.bs customer opened a support case on our end. this is in our opinion patching the issue.

### CODE REVIEW

**Review by jaapmarcus — APPROVED** [review]

**Review by BelleNottelling — APPROVED** [review]
Thank you

**Comment by KaiSchwarz-cnic** [comment]
@BelleNottelling @jaapmarcus Not sure about your exact role around FOSSBilling. Let me offer our help in case you're having any trouble with one of Team Internet's Reseller Brands which are CentralNic Reseller, HEXONET, internet.bs and TPP Wholesale. Be it about an existing Registrar Integration or in case you want to add a new one. Feel free to reach out to me.

Have a nice day!

**Comment by John-S4** [comment]
> @BelleNottelling @jaapmarcus Not sure about your exact role around FOSSBilling. Let me offer our help in case you're having any trouble with one of Team Internet's Reseller Brands which are CentralNic Reseller, HEXONET, internet.bs and TPP Wholesale. Be it about an existing Registrar Integration or in case you want to add a new one. Feel free to reach out to me.
> 
> Have a nice day!

Hi Kai. 

Obviously I'm not either of the people tagged in your reply, but let me jump in and answer anyway. Both Belle and Jaap are members of the Steering Committee of the FOSSBilling project, there are currently six of us as detailed in the [governance docs](https://github.com/FOSSBilling/FOSSBilling/blob/main/GOVERNANCE.md), and Belle is the person who is spending by far the most time at the moment maintaining and developing FOSSBilling.

We don't currently have a huge amount of working registrar modules, but we also don't have a huge amount of contributors or time. We would definitely be interested in integrations with more of them especially if there would be support and help from the registrar themselves. Thanks again for the patch for internet.bs and if your team would like to contribute to integrations with any of the other brands listed then we would definitely appreciate it.

**Comment by KaiSchwarz-cnic** [comment]
Thanks @John-S4 for adding clarification. My Team is very experienced with registrar integrations for the mentioned brands. Still, the big picture is of use for us. I understood that the [AdapterAbstract](https://github.com/FOSSBilling/FOSSBilling/blob/main/src/library/Registrar/AdapterAbstract.php) is the entry point and has to be used as reference. That's fine, but as you can imagine, there are already technical questions around.

Is the topic of additional domain fields already touched in HostBill?

**Comment by BelleNottelling** [comment]
Hi, @KaiSchwarz-cnic 

FOSSBilling is certainly a bit lacking in the number of supported registrar adapters at the moment so it would certainly be nice to see additional ones added, however the fundamental implementation of registrar adapters is lacking and I personal would put efforts towards that.

The biggest and most important missing functionality is displaying fields for certain TLDs on the checkout page. With that limitation, some TLDs that have legal requirements for certain info to be collected can't really be purchased through FOSSBilling.

**Comment by KaiSchwarz-cnic** [comment]
@BelleNottelling understood. Before you step into drafting a concept for the additional domain fields, feel free to ping me. Especially WHMCS (just picking it as most prominent example) is doing it bad in that regard and my input could therefore be valuable for you guys. In addition, IBS allows for a api-driven & by that dynamic solution and is a perfect candidate to start with.

**Comment by naeemirza** [comment]
Thank you Team Fossbilling and Team Internetbs.

**Pull request merged**
